/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package performancetasks.advancedcalculatorpackage;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.Timer;
import performancetasks.*;
/**
 *
 * @author seany
 */


public class AdvancedCalculatorV2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdvancedCalculatorV2.class.getName());
    
    private enum CalculatorModes {
        STANDARD,
        SCIENTIFIC,
        TEMPERATURE,
        TIME;
    }
    
    private CalculatorModes currentCalculatorMode = CalculatorModes.STANDARD; // Default mode  
    private JLabel currentSelectedLabel;
    
    // Sidebar Declarations
    private static final int SIDEBAR_PANEL_MAX_WIDTH = 250;
    private static final int ANIMATION_DURATION = 50;
    private static final int ANIMATION_STEP_TIME = 10;
    
    private Timer animationTimer;
    private boolean isSidebarAnimating = false;
    private boolean isSidebarExpanded = false;
    /**
     * Creates new form AdvancedCalculatorV2
     */
    public AdvancedCalculatorV2() {
        initComponents();
        initLabelListener();
        currentSelectedLabel = standardLabel;
        
        mainPanel.add(new StandardPanel(), new org.netbeans.lib.awtextra.AbsoluteConstraints
        (0, 0, mainPanel.getWidth(), mainPanel.getHeight()));
        
        setCalculatorMode(CalculatorModes.STANDARD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        collapseSidebarBtn = new javax.swing.JLabel();
        scientificLabel = new javax.swing.JLabel();
        standardLabel = new javax.swing.JLabel();
        convertersLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        calculatorLabel = new javax.swing.JLabel();
        temperatureLabel = new javax.swing.JLabel();
        goBackLabel = new javax.swing.JLabel();
        expandSidebarBtn = new javax.swing.JLabel();
        dividerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        mainPanel.setBackground(new java.awt.Color(243, 243, 243));
        mainPanel.setPreferredSize(new java.awt.Dimension(340, 530));
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainPanelMouseClicked(evt);
            }
        });
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(230, 230, 230));
        sidebarPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(225, 225, 225), null, new java.awt.Color(215, 215, 215), new java.awt.Color(183, 183, 183)));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(250, 530));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        collapseSidebarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/navbtn.png"))); // NOI18N
        collapseSidebarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        collapseSidebarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                collapseSidebarBtnMouseClicked(evt);
            }
        });
        sidebarPanel.add(collapseSidebarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 30));

        scientificLabel.setBackground(new java.awt.Color(230, 230, 230));
        scientificLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        scientificLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/Scientific.targetsize-16_contrast-white.png"))); // NOI18N
        scientificLabel.setText("Scientific");
        scientificLabel.setToolTipText("");
        scientificLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        scientificLabel.setIconTextGap(10);
        scientificLabel.setOpaque(true);
        sidebarPanel.add(scientificLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 150, 230, 40));

        standardLabel.setBackground(new java.awt.Color(223, 223, 223));
        standardLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        standardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/Segoe-MDL2-Assets-Regular-Calcul.png"))); // NOI18N
        standardLabel.setText("Standard");
        standardLabel.setDisabledIcon(null);
        standardLabel.setIconTextGap(10);
        standardLabel.setOpaque(true);
        sidebarPanel.add(standardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 100, 230, 40));

        convertersLabel.setBackground(new java.awt.Color(0, 95, 230));
        convertersLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        convertersLabel.setForeground(new java.awt.Color(87, 87, 87));
        convertersLabel.setText("Converters");
        sidebarPanel.add(convertersLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 240, -1));

        timeLabel.setBackground(new java.awt.Color(230, 230, 230));
        timeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/ClockIcon.png"))); // NOI18N
        timeLabel.setText("Time");
        timeLabel.setIconTextGap(10);
        timeLabel.setOpaque(true);
        sidebarPanel.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 230, 40));

        calculatorLabel.setBackground(new java.awt.Color(0, 95, 230));
        calculatorLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        calculatorLabel.setForeground(new java.awt.Color(87, 87, 87));
        calculatorLabel.setText("Calculator");
        sidebarPanel.add(calculatorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 240, -1));

        temperatureLabel.setBackground(new java.awt.Color(230, 230, 230));
        temperatureLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        temperatureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/temperatureicon.png"))); // NOI18N
        temperatureLabel.setText("Temperature");
        temperatureLabel.setIconTextGap(10);
        temperatureLabel.setOpaque(true);
        sidebarPanel.add(temperatureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, 40));

        goBackLabel.setBackground(new java.awt.Color(230, 230, 230));
        goBackLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        goBackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goBackLabel.setText("Go back");
        goBackLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        goBackLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        goBackLabel.setOpaque(true);
        goBackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goBackLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                goBackLabelMouseExited(evt);
            }
        });
        sidebarPanel.add(goBackLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 230, 40));

        mainPanel.add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 450));

        expandSidebarBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        expandSidebarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/navbtn.png"))); // NOI18N
        expandSidebarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        expandSidebarBtn.setIconTextGap(15);
        expandSidebarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expandSidebarBtnMouseClicked(evt);
            }
        });
        mainPanel.add(expandSidebarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 30));

        dividerPanel.setEnabled(false);
        dividerPanel.setOpaque(false);
        dividerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dividerPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dividerPanelLayout = new javax.swing.GroupLayout(dividerPanel);
        dividerPanel.setLayout(dividerPanelLayout);
        dividerPanelLayout.setHorizontalGroup(
            dividerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dividerPanelLayout.setVerticalGroup(
            dividerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        mainPanel.add(dividerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void toggleSidebar(){
        // Prevent multiple toggles at once
        if (animationTimer != null && animationTimer.isRunning()) return;

        int startWidth = sidebarPanel.getWidth();
        int endWidth = isSidebarExpanded ? 0 : SIDEBAR_PANEL_MAX_WIDTH;
        int totalSteps = ANIMATION_DURATION / ANIMATION_STEP_TIME;
        int widthStep = (endWidth - startWidth) / totalSteps;

        animationTimer = new Timer(ANIMATION_STEP_TIME, null);
        final int[] currentStep = {0};
        
        animationTimer.addActionListener(e -> {
            if (currentStep[0] >= totalSteps) {
                // Ensure final size is set
                sidebarPanel.setSize(endWidth, sidebarPanel.getHeight());
                isSidebarExpanded = !isSidebarExpanded; // Toggle state
                animationTimer.stop();
                isSidebarAnimating = false;
            } else {
                int newWidth = sidebarPanel.getWidth() + widthStep;
                sidebarPanel.setSize(newWidth, sidebarPanel.getHeight());
                currentStep[0]++;
            }
        });
        dividerPanel.setSize(340, 450);
        isSidebarAnimating = true;
        animationTimer.start();
    }
    
    private void setCalculatorMode(CalculatorModes newCalculatorMode){
        if (currentCalculatorMode == newCalculatorMode) return;
        
        currentCalculatorMode = newCalculatorMode;

        switch(currentCalculatorMode) {
            
            case STANDARD -> 
            {
                changePanelTo(new StandardPanel());
            }
            
            case SCIENTIFIC -> 
            {
                changePanelTo(new ScientificPanel());
            }
            case TEMPERATURE -> 
            {
                changePanelTo(new TemperaturePanel());
            }
            case TIME ->
            {
                changePanelTo(new TimePanel());
            }
        }
        revalidate();
        repaint();
    }
    
    private void changePanelTo(javax.swing.JPanel newPanel){
    
        for (java.awt.Component comp : mainPanel.getComponents()) {
            if (comp != null && comp != expandSidebarBtn && comp != sidebarPanel
                && comp != calculatorLabel && comp != collapseSidebarBtn
                && comp != standardLabel && comp != scientificLabel
                && comp != timeLabel && comp != temperatureLabel
                && comp != convertersLabel && comp != dividerPanel
                && comp != goBackLabel) 
            {
                mainPanel.remove(comp);
            }
        }
        
        mainPanel.add(newPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints
        (0, 0, mainPanel.getWidth(), mainPanel.getHeight()));
        
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    
    private void initLabelListener(){
        
        JLabel[] calculatorModeLabels = {
            standardLabel,
            scientificLabel,
            temperatureLabel,
            timeLabel,
        };
        
        CalculatorModes[] calculatorModes = {
            CalculatorModes.STANDARD,
            CalculatorModes.SCIENTIFIC,
            CalculatorModes.TEMPERATURE,
            CalculatorModes.TIME
        };
        
        for (int i = 0; i < calculatorModeLabels.length; i++) {
            final JLabel label = calculatorModeLabels[i];
            final CalculatorModes mode = calculatorModes[i];

            label.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent evt) {
                    if (currentSelectedLabel != null) {
                        currentSelectedLabel.setBackground(new Color(230,230,230));
                    }
                    label.setBackground(new Color(223,223,223));
                    currentSelectedLabel = label;

                    setCalculatorMode(mode);
                }

                @Override
                public void mouseEntered(MouseEvent evt) {
                    if (label != currentSelectedLabel) {
                        label.setBackground(new Color(223,223,223));
                    } else {
                        label.setBackground(new Color(237,237,237));
                    }
                }

                @Override
                public void mouseExited(MouseEvent evt) {
                    if (label != currentSelectedLabel) {
                        label.setBackground(new Color(230,230,230));
                    } else {
                        label.setBackground(new Color(223,223,223));
                    }
                }
            });
        }
        
    }
    
    
    
    private void collapseSidebarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collapseSidebarBtnMouseClicked
        toggleSidebar();
    }//GEN-LAST:event_collapseSidebarBtnMouseClicked

    private void expandSidebarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expandSidebarBtnMouseClicked
        toggleSidebar();
    }//GEN-LAST:event_expandSidebarBtnMouseClicked

    private void mainPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseClicked
        
    }//GEN-LAST:event_mainPanelMouseClicked

    private void dividerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dividerPanelMouseClicked
        Point clickPoint = evt.getPoint();
        int sidebarWidth = 250;
        
        if (isSidebarExpanded && !isSidebarAnimating && clickPoint.x > sidebarWidth) {
            toggleSidebar();
            dividerPanel.setSize(0,450);
        }
    }//GEN-LAST:event_dividerPanelMouseClicked

    private void goBackLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackLabelMouseEntered
        goBackLabel.setBackground(new Color(223,223,223));
    }//GEN-LAST:event_goBackLabelMouseEntered

    private void goBackLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackLabelMouseExited
        goBackLabel.setBackground(new Color(230,230,230));
    }//GEN-LAST:event_goBackLabelMouseExited

    private void goBackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackLabelMouseClicked
        ApplicationsMenu appMenu = new ApplicationsMenu();
        this.dispose();
        appMenu.setLocationRelativeTo(this);
        appMenu.setVisible(true);
    }//GEN-LAST:event_goBackLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdvancedCalculatorV2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calculatorLabel;
    private javax.swing.JLabel collapseSidebarBtn;
    private javax.swing.JLabel convertersLabel;
    private javax.swing.JPanel dividerPanel;
    private javax.swing.JLabel expandSidebarBtn;
    private javax.swing.JLabel goBackLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel scientificLabel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel standardLabel;
    private javax.swing.JLabel temperatureLabel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
