/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package performancetasks.advancedcalculatorpackage;

import java.awt.Font;
import java.awt.FontMetrics;
import java.math.BigDecimal;
import java.math.MathContext;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import javax.swing.JLabel;

/**
 * To do list
 * Fix Decimal Bug, cannot input 0 after decimal point
 * Fix Comments
 * Add Unary Operations
 * Add Memory overflow protection
 */



/**
 *
 * @author seany
 */
public class StandardPanel extends javax.swing.JPanel {
   // For Display 
    private final DecimalFormat decimalFormat = new DecimalFormat("#,##0.################");
    private String historyDisplay = ""; // For Nested Operations
    
    // For Calculation
    private BigDecimal num1 = BigDecimal.ZERO;
    private BigDecimal lastNum2 = BigDecimal.ZERO; // Last second number (for repeating =)
    private BigDecimal result = BigDecimal.ZERO;
    
    private char operator = 0;
    private final MathContext mc = new MathContext(16, RoundingMode.HALF_UP);
    private final int MAX_INPUT_LENGTH = 16;
    private boolean newInput = true;
    private boolean justCalculated = false;
    
    /**
     * Creates new form standardPanel
     */
    public StandardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayPanel = new javax.swing.JPanel();
        txtHistory = new javax.swing.JLabel();
        StandardLabel = new javax.swing.JLabel();
        txtDisplay = new javax.swing.JLabel();
        ButtonsPanel = new javax.swing.JPanel();
        backspaceBtn = new javax.swing.JButton();
        clearEntryBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        negateBtn = new javax.swing.JButton();
        percentBtn = new javax.swing.JButton();
        reciprocalBtn = new javax.swing.JButton();
        xSquaredBtn = new javax.swing.JButton();
        squarerootofXBtn = new javax.swing.JButton();
        divideBtn = new javax.swing.JButton();
        sevenBtn = new javax.swing.JButton();
        eightBtn = new javax.swing.JButton();
        nineBtn = new javax.swing.JButton();
        multiplyBtn = new javax.swing.JButton();
        subtractBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        fourBtn = new javax.swing.JButton();
        oneBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        equalToBtn = new javax.swing.JButton();
        decimalBtn = new javax.swing.JButton();
        zeroBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 243, 243));
        setPreferredSize(new java.awt.Dimension(340, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DisplayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHistory.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        txtHistory.setForeground(new java.awt.Color(97, 97, 97));
        txtHistory.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtHistory.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        txtHistory.setOpaque(true);
        DisplayPanel.add(txtHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 320, 40));

        StandardLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        StandardLabel.setText("Standard");
        StandardLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DisplayPanel.add(StandardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 35));

        txtDisplay.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        txtDisplay.setForeground(new java.awt.Color(0, 0, 0));
        txtDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtDisplay.setText("0");
        txtDisplay.setOpaque(true);
        DisplayPanel.add(txtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 50));

        add(DisplayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 160));

        ButtonsPanel.setPreferredSize(new java.awt.Dimension(340, 290));
        ButtonsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backspaceBtn.setBackground(new java.awt.Color(249, 249, 249));
        backspaceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/backspace.png"))); // NOI18N
        backspaceBtn.setFocusPainted(false);
        backspaceBtn.setFocusable(false);
        backspaceBtn.setRequestFocusEnabled(false);
        backspaceBtn.setRolloverEnabled(false);
        backspaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(backspaceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 0, 86, 50));

        clearEntryBtn.setBackground(new java.awt.Color(249, 249, 249));
        clearEntryBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearEntryBtn.setText("CE");
        clearEntryBtn.setFocusPainted(false);
        clearEntryBtn.setFocusable(false);
        clearEntryBtn.setRequestFocusEnabled(false);
        clearEntryBtn.setRolloverEnabled(false);
        clearEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEntryBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(clearEntryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, 86, 50));

        clearBtn.setBackground(new java.awt.Color(249, 249, 249));
        clearBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearBtn.setText("C");
        clearBtn.setToolTipText("");
        clearBtn.setFocusPainted(false);
        clearBtn.setFocusable(false);
        clearBtn.setRequestFocusEnabled(false);
        clearBtn.setRolloverEnabled(false);
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 0, 86, 50));

        negateBtn.setBackground(new java.awt.Color(249, 249, 249));
        negateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/negate.png"))); // NOI18N
        negateBtn.setFocusPainted(false);
        negateBtn.setFocusable(false);
        negateBtn.setRequestFocusEnabled(false);
        negateBtn.setRolloverEnabled(false);
        negateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negateBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(negateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 240, 86, 50));

        percentBtn.setBackground(new java.awt.Color(249, 249, 249));
        percentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/percentage.png"))); // NOI18N
        percentBtn.setFocusPainted(false);
        percentBtn.setFocusable(false);
        percentBtn.setRequestFocusEnabled(false);
        percentBtn.setRolloverEnabled(false);
        percentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(percentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 86, 50));

        reciprocalBtn.setBackground(new java.awt.Color(249, 249, 249));
        reciprocalBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reciprocalBtn.setText("1/x");
        reciprocalBtn.setFocusPainted(false);
        reciprocalBtn.setFocusable(false);
        reciprocalBtn.setRequestFocusEnabled(false);
        reciprocalBtn.setRolloverEnabled(false);
        reciprocalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reciprocalBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(reciprocalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 48, 86, 50));

        xSquaredBtn.setBackground(new java.awt.Color(249, 249, 249));
        xSquaredBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        xSquaredBtn.setText("x²");
        xSquaredBtn.setFocusPainted(false);
        xSquaredBtn.setFocusable(false);
        xSquaredBtn.setRequestFocusEnabled(false);
        xSquaredBtn.setRolloverEnabled(false);
        xSquaredBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xSquaredBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(xSquaredBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 48, 86, 50));

        squarerootofXBtn.setBackground(new java.awt.Color(249, 249, 249));
        squarerootofXBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        squarerootofXBtn.setText("²√x");
        squarerootofXBtn.setFocusPainted(false);
        squarerootofXBtn.setFocusable(false);
        squarerootofXBtn.setRequestFocusEnabled(false);
        squarerootofXBtn.setRolloverEnabled(false);
        squarerootofXBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squarerootofXBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(squarerootofXBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 48, 86, 50));

        divideBtn.setBackground(new java.awt.Color(249, 249, 249));
        divideBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/divide.png"))); // NOI18N
        divideBtn.setFocusPainted(false);
        divideBtn.setFocusable(false);
        divideBtn.setRequestFocusEnabled(false);
        divideBtn.setRolloverEnabled(false);
        divideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(divideBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 48, 86, 50));

        sevenBtn.setBackground(new java.awt.Color(249, 249, 249));
        sevenBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sevenBtn.setText("7");
        sevenBtn.setFocusPainted(false);
        sevenBtn.setFocusable(false);
        sevenBtn.setRequestFocusEnabled(false);
        sevenBtn.setRolloverEnabled(false);
        sevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(sevenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 96, 86, 50));

        eightBtn.setBackground(new java.awt.Color(249, 249, 249));
        eightBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eightBtn.setText("8");
        eightBtn.setFocusPainted(false);
        eightBtn.setFocusable(false);
        eightBtn.setRequestFocusEnabled(false);
        eightBtn.setRolloverEnabled(false);
        eightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(eightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 96, 86, 50));

        nineBtn.setBackground(new java.awt.Color(249, 249, 249));
        nineBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nineBtn.setText("9");
        nineBtn.setFocusPainted(false);
        nineBtn.setFocusable(false);
        nineBtn.setRequestFocusEnabled(false);
        nineBtn.setRolloverEnabled(false);
        nineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(nineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 96, 86, 50));

        multiplyBtn.setBackground(new java.awt.Color(249, 249, 249));
        multiplyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/multiplication.png"))); // NOI18N
        multiplyBtn.setFocusPainted(false);
        multiplyBtn.setFocusable(false);
        multiplyBtn.setRequestFocusEnabled(false);
        multiplyBtn.setRolloverEnabled(false);
        multiplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(multiplyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 96, 86, 50));

        subtractBtn.setBackground(new java.awt.Color(249, 249, 249));
        subtractBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/subtraction.png"))); // NOI18N
        subtractBtn.setFocusPainted(false);
        subtractBtn.setFocusable(false);
        subtractBtn.setRequestFocusEnabled(false);
        subtractBtn.setRolloverEnabled(false);
        subtractBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(subtractBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 144, 86, 50));

        sixBtn.setBackground(new java.awt.Color(249, 249, 249));
        sixBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sixBtn.setText("6");
        sixBtn.setFocusPainted(false);
        sixBtn.setFocusable(false);
        sixBtn.setRequestFocusEnabled(false);
        sixBtn.setRolloverEnabled(false);
        sixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(sixBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 144, 86, 50));

        fiveBtn.setBackground(new java.awt.Color(249, 249, 249));
        fiveBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fiveBtn.setText("5");
        fiveBtn.setFocusPainted(false);
        fiveBtn.setFocusable(false);
        fiveBtn.setRequestFocusEnabled(false);
        fiveBtn.setRolloverEnabled(false);
        fiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(fiveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 144, 86, 50));

        fourBtn.setBackground(new java.awt.Color(249, 249, 249));
        fourBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fourBtn.setText("4");
        fourBtn.setFocusPainted(false);
        fourBtn.setFocusable(false);
        fourBtn.setRequestFocusEnabled(false);
        fourBtn.setRolloverEnabled(false);
        fourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(fourBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 144, 86, 50));

        oneBtn.setBackground(new java.awt.Color(249, 249, 249));
        oneBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        oneBtn.setText("1");
        oneBtn.setFocusPainted(false);
        oneBtn.setFocusable(false);
        oneBtn.setRequestFocusEnabled(false);
        oneBtn.setRolloverEnabled(false);
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(oneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 192, 86, 50));

        twoBtn.setBackground(new java.awt.Color(249, 249, 249));
        twoBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        twoBtn.setText("2");
        twoBtn.setToolTipText("");
        twoBtn.setFocusPainted(false);
        twoBtn.setFocusable(false);
        twoBtn.setRequestFocusEnabled(false);
        twoBtn.setRolloverEnabled(false);
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(twoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 192, 86, 50));

        threeBtn.setBackground(new java.awt.Color(249, 249, 249));
        threeBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        threeBtn.setText("3");
        threeBtn.setFocusPainted(false);
        threeBtn.setFocusable(false);
        threeBtn.setRequestFocusEnabled(false);
        threeBtn.setRolloverEnabled(false);
        threeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(threeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 192, 86, 50));

        addBtn.setBackground(new java.awt.Color(249, 249, 249));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/addition.png"))); // NOI18N
        addBtn.setFocusPainted(false);
        addBtn.setFocusable(false);
        addBtn.setRequestFocusEnabled(false);
        addBtn.setRolloverEnabled(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 192, 86, 50));

        equalToBtn.setBackground(new java.awt.Color(25, 106, 167));
        equalToBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/equalto.png"))); // NOI18N
        equalToBtn.setBorderPainted(false);
        equalToBtn.setRequestFocusEnabled(false);
        equalToBtn.setRolloverEnabled(false);
        equalToBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalToBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(equalToBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 240, 86, 50));

        decimalBtn.setBackground(new java.awt.Color(249, 249, 249));
        decimalBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        decimalBtn.setText(".");
        decimalBtn.setToolTipText("");
        decimalBtn.setFocusPainted(false);
        decimalBtn.setFocusable(false);
        decimalBtn.setRequestFocusEnabled(false);
        decimalBtn.setRolloverEnabled(false);
        decimalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(decimalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 240, 86, 50));

        zeroBtn.setBackground(new java.awt.Color(249, 249, 249));
        zeroBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        zeroBtn.setText("0");
        zeroBtn.setToolTipText("");
        zeroBtn.setFocusPainted(false);
        zeroBtn.setFocusable(false);
        zeroBtn.setRequestFocusEnabled(false);
        zeroBtn.setRolloverEnabled(false);
        zeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(zeroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 240, 86, 50));

        add(ButtonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 340, 290));
    }// </editor-fold>//GEN-END:initComponents
    
    /*
        Format BigDecimal into string for display (removes trailing zeros, and adds commas)
    */
    private String formatNumber(BigDecimal number) {
        // Removes unnecessary zeros
        BigDecimal strippedNumber = number.stripTrailingZeros();
        
        // If it's a whole number, format with commas
        if(strippedNumber.scale() <= 0) {
            return String.format("%,d", strippedNumber.toBigInteger());
        }
        
        // Otherwise use decimal format
        return decimalFormat.format(number);
    }
    
    /*
        Parse display text to BigDecimal for calculation (removes commas)
    */
    private BigDecimal parseDisplay(){
        try {
            String text = txtDisplay.getText().replace(",", "");
            return new BigDecimal(text);
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }
    
    /*
        Check if display shows an error message
    */
    private boolean isError(){
        String text = txtDisplay.getText();
        return text.equals("Cannot divide by zero") ||
            text.equals("Invalid input") ||
            text.equals("Error");
    }
    
    /*
        Append number to display
    */
    private void appendNumber(String number) {
        String currentText = txtDisplay.getText();
        
        // Clear display on new input or when error occurs, start fresh
        if (newInput || isError()) {
            txtDisplay.setText(number);
            newInput = false;
            justCalculated = false;
            resizeLabel(txtDisplay);
            return;
        }
        // Removes commas for manipulation
        String unformatted = currentText.replace(",", "");
        
        
        if (unformatted.equals("0") && !number.equals("0.")) {
            txtDisplay.setText(number);
            resizeLabel(txtDisplay);
            return;
        }
        
        // Check max length (without commas and decimal point)
        String textWithoutFormat = unformatted.replace(".", "".replace("-",""));
        if (textWithoutFormat.length() >= MAX_INPUT_LENGTH) {
            return;
        }
        
        // Append number
        txtDisplay.setText(unformatted + number);
        formatAndResize();
        
    }
    
    /*
        Format display with commas and resize
    */
    private void formatAndResize() {
        String currentText = txtDisplay.getText().replace(",", "");
        
        // Don't format if ending with a decimal point
        if (currentText.endsWith(".")) {
            resizeLabel(txtDisplay);
            return;
        }
        
        try {
            BigDecimal value = new BigDecimal(currentText);
            txtDisplay.setText(formatNumber(value));
        } catch (NumberFormatException e) {
            
        }
        
        resizeLabel(txtDisplay);
    }
    
    /*
        Set operator and prepare for next input
    */
    private void setOperator(char op) {
        if (!isError()) {
            // If there is already an operator, calculate first
            if (operator != 0 && !newInput) {
                calculate();
                num1 = result;
            } else {
                num1 = parseDisplay();
            }
        }
            operator = op;
            txtHistory.setText(formatNumber(num1) + " " + operator);
            newInput = true;
            justCalculated = false;
    }
    
    /*
        Perform calculation
    */
    private void calculate(){
        // if no operator selected, just format and display current number
        if (operator == 0) {
            if (!isError()) {
                num1 = parseDisplay();  
                txtDisplay.setText(formatNumber(num1));
            }

            txtHistory.setText("");
            newInput = true;
            justCalculated = false;
            resizeLabel(txtDisplay);
            return;
        }
        
        BigDecimal num2;

        // Use new input or repeat last operation
        if (!justCalculated) {
            num2 = parseDisplay();
            lastNum2 = num2;
        } else {
            num2 = lastNum2;
            //
        }
        try{
            switch (operator) {
                case '+' -> result = num1.add(num2, mc);
                case '-' -> result = num1.subtract(num2, mc);
                case '×' -> result = num1.multiply(num2, mc);
                case '÷' -> {
                    if (num2.compareTo(BigDecimal.ZERO) == 0) {
                        txtDisplay.setText("Cannot divide by zero");
                        txtHistory.setText(formatNumber(num1) + " ÷ " + formatNumber(num2) + " =");
                        resizeLabel(txtDisplay);
                        operator = 0;
                        newInput = true;
                        return;
                    }
                    result =  num1.divide(num2, mc);
                }
            }
            
            txtHistory.setText(formatNumber(num1) + " " + operator + " " + formatNumber(num2) + " =");
            txtDisplay.setText(formatNumber(result));
            num1 = result;
            
        } catch(ArithmeticException e){
            txtDisplay.setText("Error");
        }

        newInput = true;
        justCalculated = true;
        resizeLabel(txtDisplay);
    }
    
    private void backspaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceBtnActionPerformed
        String text = txtDisplay.getText();
        
        // Clear history if starting new input
        if (newInput){
            txtHistory.setText("");
            return;
        }
        
        // Reset on error
        if (isError()) {
            txtDisplay.setText("0");
            resetFontSize();
            return;
        }
        
        // Remove commas for manipulation
        String unformatted = text.replace(",","");
       
        if (unformatted.length() > 1) {
            String newText = unformatted.substring(0, unformatted.length() - 1);
            
            // If only "-" remains, reset to 0
            if (newText.equals("-")) {
                txtDisplay.setText("0");
                resetFontSize();
            } else {
                txtDisplay.setText(newText);
                formatAndResize();
            }
        } else {
            txtDisplay.setText("0");
            resetFontSize();
        }
    }//GEN-LAST:event_backspaceBtnActionPerformed

    private void clearEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearEntryBtnActionPerformed
        txtDisplay.setText("0");
        newInput = true;
        resetFontSize();
    }//GEN-LAST:event_clearEntryBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        txtDisplay.setText("0");
        txtHistory.setText("");
        num1 = BigDecimal.ZERO;
        operator = 0;
        lastNum2 = BigDecimal.ZERO;
        newInput = true;
        justCalculated = false;
        historyDisplay = "";
        resetFontSize();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void zeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtnActionPerformed
        appendNumber("0");
    }//GEN-LAST:event_zeroBtnActionPerformed

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
        appendNumber("1");
    }//GEN-LAST:event_oneBtnActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        appendNumber("2");
    }//GEN-LAST:event_twoBtnActionPerformed

    private void threeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtnActionPerformed
        appendNumber("3");
    }//GEN-LAST:event_threeBtnActionPerformed

    private void fourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtnActionPerformed
        appendNumber("4");
    }//GEN-LAST:event_fourBtnActionPerformed

    private void fiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtnActionPerformed
        appendNumber("5");
    }//GEN-LAST:event_fiveBtnActionPerformed

    private void sixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtnActionPerformed
        appendNumber("6");
    }//GEN-LAST:event_sixBtnActionPerformed

    private void sevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBtnActionPerformed
        appendNumber("7");
    }//GEN-LAST:event_sevenBtnActionPerformed

    private void eightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtnActionPerformed
        appendNumber("8");
    }//GEN-LAST:event_eightBtnActionPerformed

    private void nineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtnActionPerformed
        appendNumber("9");
    }//GEN-LAST:event_nineBtnActionPerformed

    private void decimalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalBtnActionPerformed
        String currentText = txtDisplay.getText();
        
        if (newInput || isError()) {
            txtDisplay.setText("0.");
            newInput = false;
            resizeLabel(txtDisplay);
            return;
        }
        
        if (!currentText.contains(".")) {
            txtDisplay.setText(currentText + ".");
            resizeLabel(txtDisplay);
        }
    }//GEN-LAST:event_decimalBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        setOperator('+');
    }//GEN-LAST:event_addBtnActionPerformed

    private void subtractBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractBtnActionPerformed
        setOperator('-');
    }//GEN-LAST:event_subtractBtnActionPerformed

    private void multiplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyBtnActionPerformed
        setOperator('×');
    }//GEN-LAST:event_multiplyBtnActionPerformed

    private void divideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideBtnActionPerformed
        setOperator('÷');
    }//GEN-LAST:event_divideBtnActionPerformed

    private void percentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentBtnActionPerformed
        try {
            num1 = parseDisplay();
            result = num1.divide(new BigDecimal("100"), mc);
            txtDisplay.setText(formatNumber(result));
            txtHistory.setText(formatNumber(num1) + " ÷ 100");
            newInput = false;
            resizeLabel(txtDisplay);
        } catch (NumberFormatException e){
            txtDisplay.setText("Error");
            resizeLabel(txtDisplay);
        }
    }//GEN-LAST:event_percentBtnActionPerformed

    private void negateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negateBtnActionPerformed
        if (isError()) {
            return;
        }
        BigDecimal currentNum = parseDisplay();
        BigDecimal negateNum = currentNum.negate();
        txtDisplay.setText(formatNumber(negateNum));
        if (operator != 0) {
            txtHistory.setText(currentNum + " " + operator + " negate( " + formatNumber(currentNum) + " )");
        }
        newInput = false;
        resizeLabel(txtDisplay);
    }//GEN-LAST:event_negateBtnActionPerformed

    private void reciprocalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reciprocalBtnActionPerformed
        // WIP
    }//GEN-LAST:event_reciprocalBtnActionPerformed
    
    private void xSquaredBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xSquaredBtnActionPerformed
        // WIP
    }//GEN-LAST:event_xSquaredBtnActionPerformed

    private void squarerootofXBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squarerootofXBtnActionPerformed
        // WIP
    }//GEN-LAST:event_squarerootofXBtnActionPerformed

    private void equalToBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalToBtnActionPerformed
        calculate();
    }//GEN-LAST:event_equalToBtnActionPerformed
    
    private void resizeLabel(JLabel label){
        String text = label.getText();
        if (text.isEmpty()) return;
        
        int fontSize = 36; // Default Font Size
        Font font = label.getFont().deriveFont((float) fontSize);
        FontMetrics metrics = label.getFontMetrics(font);

        int labelWidth = label.getWidth();
        int labelHeight = label.getHeight();

        // Decrease font size until text fits within label
        while ((metrics.stringWidth(text) > labelWidth || metrics.getHeight() > labelHeight) && fontSize > 8) {
            fontSize -= 1;
            font = label.getFont().deriveFont((float) fontSize);
            metrics = label.getFontMetrics(font);
        }

        label.setFont(font);
    }
    
    private void resetFontSize() {
        Font font = txtDisplay.getFont().deriveFont(36f);
        txtDisplay.setFont(font);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JLabel StandardLabel;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backspaceBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton clearEntryBtn;
    private javax.swing.JButton decimalBtn;
    private javax.swing.JButton divideBtn;
    private javax.swing.JButton eightBtn;
    private javax.swing.JButton equalToBtn;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton fourBtn;
    private javax.swing.JButton multiplyBtn;
    private javax.swing.JButton negateBtn;
    private javax.swing.JButton nineBtn;
    private javax.swing.JButton oneBtn;
    private javax.swing.JButton percentBtn;
    private javax.swing.JButton reciprocalBtn;
    private javax.swing.JButton sevenBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton squarerootofXBtn;
    private javax.swing.JButton subtractBtn;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton twoBtn;
    private javax.swing.JLabel txtDisplay;
    private javax.swing.JLabel txtHistory;
    private javax.swing.JButton xSquaredBtn;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration//GEN-END:variables
}
