/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package performancetasks.advancedcalculatorpackage;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.math.BigDecimal;
import java.math.MathContext;
import java.math.RoundingMode;
import java.text.NumberFormat;
import javax.swing.JLabel;

/**
 *
 * @author seany
 */
public class TimePanel extends javax.swing.JPanel {
    // For Display
    private final Font semiboldFont = new Font("Segoe UI Semibold", Font.PLAIN, 36);
    private final Font semilightFont = new Font("Segoe UI Semilight", Font.PLAIN, 36);
    private static boolean enabledDisplay = true; // enabled = txtDisplay1   disabled = txtDisplay2;
    //For Conversion
    private final MathContext mc;
    private final NumberFormat numberFormat = NumberFormat.getNumberInstance();
    
    private boolean newInput = true;
    private BigDecimal result = BigDecimal.ZERO;
    private UnitOfTime fromUnit;
    private UnitOfTime toUnit;
    private int from;
    private int to;
    
    private enum UnitOfTime{
        MICROSECONDS,
        MILLISECONDS,
        SECONDS,
        MINUTES,
        HOURS,
        DAYS,
        WEEKS,
        YEARS;
    };
    
    
    /**
     * Creates new form TimePanel
     */
    public TimePanel() {
        this.mc = new MathContext(16, RoundingMode.HALF_UP);
        initComponents();
        initLabelListeners();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayPanel = new javax.swing.JPanel();
        TimeLabel = new javax.swing.JLabel();
        txtDisplay2 = new javax.swing.JLabel();
        unitComboBox2 = new javax.swing.JComboBox<>();
        txtDisplay1 = new javax.swing.JLabel();
        unitComboBox1 = new javax.swing.JComboBox<>();
        ButtonsLabel = new javax.swing.JPanel();
        backspaceBtn = new javax.swing.JButton();
        clearEntryBtn = new javax.swing.JButton();
        eightBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        sevenBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        decimalBtn = new javax.swing.JButton();
        oneBtn = new javax.swing.JButton();
        fourBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        zeroBtn = new javax.swing.JButton();
        nineBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(340, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DisplayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TimeLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        TimeLabel.setText("Time");
        TimeLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DisplayPanel.add(TimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 35));

        txtDisplay2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        txtDisplay2.setText("0");
        txtDisplay2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDisplay2MouseClicked(evt);
            }
        });
        DisplayPanel.add(txtDisplay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        unitComboBox2.setMaximumRowCount(8);
        unitComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Microseconds", "Milliseconds", "Seconds", "Minutes", "Hours", "Days", "Weeks", "Years" }));
        unitComboBox2.setSelectedIndex(4);
        unitComboBox2.setBorder(null);
        unitComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DisplayPanel.add(unitComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtDisplay1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        txtDisplay1.setText("0");
        txtDisplay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDisplay1MouseClicked(evt);
            }
        });
        DisplayPanel.add(txtDisplay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        unitComboBox1.setMaximumRowCount(8);
        unitComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Microseconds", "Milliseconds", "Seconds", "Minutes", "Hours", "Days", "Weeks", "Years" }));
        unitComboBox1.setSelectedIndex(3);
        unitComboBox1.setBorder(null);
        unitComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DisplayPanel.add(unitComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        add(DisplayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 240));

        ButtonsLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backspaceBtn.setBackground(new java.awt.Color(249, 249, 249));
        backspaceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/backspace.png"))); // NOI18N
        backspaceBtn.setFocusPainted(false);
        backspaceBtn.setFocusable(false);
        backspaceBtn.setRequestFocusEnabled(false);
        backspaceBtn.setRolloverEnabled(false);
        backspaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(backspaceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 0, 80, 50));

        clearEntryBtn.setBackground(new java.awt.Color(249, 249, 249));
        clearEntryBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearEntryBtn.setText("CE");
        clearEntryBtn.setFocusPainted(false);
        clearEntryBtn.setFocusable(false);
        clearEntryBtn.setRequestFocusEnabled(false);
        clearEntryBtn.setRolloverEnabled(false);
        clearEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEntryBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(clearEntryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 50, 80, 50));

        eightBtn.setBackground(new java.awt.Color(249, 249, 249));
        eightBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eightBtn.setText("8");
        eightBtn.setFocusPainted(false);
        eightBtn.setFocusable(false);
        eightBtn.setRequestFocusEnabled(false);
        eightBtn.setRolloverEnabled(false);
        eightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(eightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 0, 80, 50));

        fiveBtn.setBackground(new java.awt.Color(249, 249, 249));
        fiveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fiveBtn.setText("5");
        fiveBtn.setFocusPainted(false);
        fiveBtn.setFocusable(false);
        fiveBtn.setRequestFocusEnabled(false);
        fiveBtn.setRolloverEnabled(false);
        fiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(fiveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 50, 80, 50));

        sevenBtn.setBackground(new java.awt.Color(249, 249, 249));
        sevenBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sevenBtn.setText("7");
        sevenBtn.setFocusPainted(false);
        sevenBtn.setFocusable(false);
        sevenBtn.setRequestFocusEnabled(false);
        sevenBtn.setRolloverEnabled(false);
        sevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(sevenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 80, 50));

        threeBtn.setBackground(new java.awt.Color(249, 249, 249));
        threeBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        threeBtn.setText("3");
        threeBtn.setFocusPainted(false);
        threeBtn.setFocusable(false);
        threeBtn.setRequestFocusEnabled(false);
        threeBtn.setRolloverEnabled(false);
        threeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(threeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 100, 80, 50));

        decimalBtn.setBackground(new java.awt.Color(249, 249, 249));
        decimalBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        decimalBtn.setText(".");
        decimalBtn.setFocusPainted(false);
        decimalBtn.setFocusable(false);
        decimalBtn.setRequestFocusEnabled(false);
        decimalBtn.setRolloverEnabled(false);
        decimalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(decimalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 150, 80, 50));

        oneBtn.setBackground(new java.awt.Color(249, 249, 249));
        oneBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        oneBtn.setText("1");
        oneBtn.setFocusPainted(false);
        oneBtn.setFocusable(false);
        oneBtn.setRequestFocusEnabled(false);
        oneBtn.setRolloverEnabled(false);
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(oneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 100, 80, 50));

        fourBtn.setBackground(new java.awt.Color(249, 249, 249));
        fourBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fourBtn.setText("4");
        fourBtn.setFocusPainted(false);
        fourBtn.setFocusable(false);
        fourBtn.setRequestFocusEnabled(false);
        fourBtn.setRolloverEnabled(false);
        fourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(fourBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 50, 80, 50));

        twoBtn.setBackground(new java.awt.Color(249, 249, 249));
        twoBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        twoBtn.setText("2");
        twoBtn.setFocusPainted(false);
        twoBtn.setFocusable(false);
        twoBtn.setRequestFocusEnabled(false);
        twoBtn.setRolloverEnabled(false);
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(twoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 100, 80, 50));

        zeroBtn.setBackground(new java.awt.Color(249, 249, 249));
        zeroBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        zeroBtn.setText("0");
        zeroBtn.setFocusPainted(false);
        zeroBtn.setFocusable(false);
        zeroBtn.setRequestFocusEnabled(false);
        zeroBtn.setRolloverEnabled(false);
        zeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(zeroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 150, 80, 50));

        nineBtn.setBackground(new java.awt.Color(249, 249, 249));
        nineBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nineBtn.setText("9");
        nineBtn.setFocusPainted(false);
        nineBtn.setFocusable(false);
        nineBtn.setRequestFocusEnabled(false);
        nineBtn.setRolloverEnabled(false);
        nineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(nineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 0, 80, 50));

        sixBtn.setBackground(new java.awt.Color(249, 249, 249));
        sixBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sixBtn.setText("6");
        sixBtn.setFocusPainted(false);
        sixBtn.setFocusable(false);
        sixBtn.setRequestFocusEnabled(false);
        sixBtn.setRolloverEnabled(false);
        sixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(sixBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 50, 80, 50));

        add(ButtonsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 340, 210));
    }// </editor-fold>//GEN-END:initComponents

    
    private void initLabelListeners(){
//        JLabel[] displayLabels = {
//            txtDisplay1,
//            txtDisplay2
//        };
//        from = unitComboBox1.getSelectedIndex();
//        to = unitComboBox2.getSelectedIndex();
//        
//        fromUnit = UnitOfTime.values()[from];
//        toUnit = UnitOfTime.values()[to];
//        
//        for(int i = 0; i < displayLabels.length; i++){
//            JLabel label = displayLabels[i];
//            label.addPropertyChangeListener((PropertyChangeEvent evt) -> {
//                if (enabledDisplay) {
//                    double num1 = Double.parseDouble(txtDisplay1.getText());
//                    txtDisplay2.setText(String.valueOf(convertTime(num1, fromUnit, toUnit)));
//                } else {
//                    double num2 = Double.parseDouble(txtDisplay2.getText());
//                }
//            });
//        }
    unitComboBox1.addActionListener(e -> updateConversion());
    unitComboBox2.addActionListener(e -> updateConversion());
//    addDocumentListener(txtDisplay1);
//    addDocumentListener(txtDisplay2);
    }
    
//    private void addDocumentListener(JTextField textField) {
//    textField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
//        public void insertUpdate(javax.swing.event.DocumentEvent e) {
//            updateConversion();
//        }
//        public void removeUpdate(javax.swing.event.DocumentEvent e) {
//            updateConversion();
//        }
//        public void changedUpdate(javax.swing.event.DocumentEvent e) {
//            updateConversion();
//        }
//    });
//}
    
    private JLabel getEnabledDisplay(){
        if (enabledDisplay) { 
            return txtDisplay1;
        }
        return txtDisplay2;
    }
    
    private void updateConversion(){
        BigDecimal num;
        if (enabledDisplay) {
            num = new BigDecimal(txtDisplay1.getText());
        } else {
            num = new BigDecimal(txtDisplay2.getText());
        }
        
        from = unitComboBox1.getSelectedIndex();
        to = unitComboBox2.getSelectedIndex();
        
        fromUnit = UnitOfTime.values()[from];
        toUnit = UnitOfTime.values()[to];
        
        result = convertTime(num, fromUnit, toUnit);
        
        String formattedResult = numberFormat.format(result);
        
        if(enabledDisplay){
            txtDisplay2.setText(formattedResult);
        } else {
            txtDisplay1.setText(formattedResult);
        }
    }
    
    private void displayLabel(String text) {
        String currentText = getEnabledDisplay().getText();
        if (currentText.equals("0")){
            getEnabledDisplay().setText(text);
            return;
        }
        getEnabledDisplay().setText(getEnabledDisplay().getText() + text);
    }
    
    public BigDecimal convertTime(BigDecimal value, UnitOfTime fromUnit, UnitOfTime toUnit) {
        // Convert from the source unit to microseconds
        BigDecimal microseconds = toMicroseconds(value, fromUnit);
        // Convert from microseconds to the target unit
        return fromMicroseconds(microseconds, toUnit);
    }

    private BigDecimal toMicroseconds(BigDecimal value, UnitOfTime unit) {
        switch (unit) {
            case MICROSECONDS -> {
                return value;
            }
            case MILLISECONDS -> {
                return value.multiply(BigDecimal.valueOf(1_000));
            }
            case SECONDS -> {
                return value.multiply(BigDecimal.valueOf(1_000_000));
            }
            case MINUTES -> {
                return value.multiply(BigDecimal.valueOf(60))
                        .multiply(BigDecimal.valueOf(1_000_000));
            }
            case HOURS -> {
                return value.multiply(BigDecimal.valueOf(60)
                        .multiply(BigDecimal.valueOf(60))
                        .multiply(BigDecimal.valueOf(1_000_000)));
            }
            case DAYS -> {
                return value.multiply(BigDecimal.valueOf(24)
                        .multiply(BigDecimal.valueOf(60)
                        .multiply(BigDecimal.valueOf(60))
                        .multiply(BigDecimal.valueOf(1_000_000))));
            }
            case WEEKS -> {
                return value.multiply(BigDecimal.valueOf(7)
                        .multiply(BigDecimal.valueOf(24)
                        .multiply(BigDecimal.valueOf(60)
                        .multiply(BigDecimal.valueOf(60))
                        .multiply(BigDecimal.valueOf(1_000_000)))));
            }
            case YEARS -> {
                return value.multiply(BigDecimal.valueOf(365.25)
                        .multiply(BigDecimal.valueOf(24)
                        .multiply(BigDecimal.valueOf(60)
                        .multiply(BigDecimal.valueOf(60))
                        .multiply(BigDecimal.valueOf(1_000_000)))));
            }
            default -> { return BigDecimal.ZERO; }
        }
    }

    private BigDecimal fromMicroseconds(BigDecimal microseconds, UnitOfTime unit) {
        switch (unit) {
            case MICROSECONDS -> {
                return microseconds;
            }
            case MILLISECONDS -> {
                return microseconds.divide(BigDecimal.valueOf(1_000), mc);
            }
            case SECONDS -> {
                return microseconds.divide(BigDecimal.valueOf(1_000_000), mc);
            }
            case MINUTES -> {
                return microseconds.divide(BigDecimal.valueOf(60)
                        .multiply(BigDecimal.valueOf(1_000_000)), mc);
            }
            case HOURS -> {
                return microseconds.divide(BigDecimal.valueOf(60)
                        .multiply(BigDecimal.valueOf(60)
                        .multiply(BigDecimal.valueOf(1_000_000))), mc);
            }
            case DAYS -> {
                return microseconds.divide(BigDecimal.valueOf(24)
                        .multiply(BigDecimal.valueOf(60)
                        .multiply(BigDecimal.valueOf(60)
                        .multiply(BigDecimal.valueOf(1_000_000)))), mc);
            }
            case WEEKS -> {
                return microseconds.divide(BigDecimal.valueOf(7)
                        .multiply(BigDecimal.valueOf(24)
                        .multiply(BigDecimal.valueOf(60)
                        .multiply(BigDecimal.valueOf(60)
                        .multiply(BigDecimal.valueOf(1_000_000))))), mc);
            }
            case YEARS -> {
                return microseconds.divide(BigDecimal.valueOf(365.25)
                        .multiply(BigDecimal.valueOf(24)
                        .multiply(BigDecimal.valueOf(60)
                        .multiply(BigDecimal.valueOf(60)
                        .multiply(BigDecimal.valueOf(1_000_000))))), mc);
            }
            default -> { return BigDecimal.ZERO; }
        }
    }
    
    private void backspaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceBtnActionPerformed
        updateConversion();
    }//GEN-LAST:event_backspaceBtnActionPerformed
    
    private void clearEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearEntryBtnActionPerformed
        if(enabledDisplay) {
            txtDisplay1.setText("0");
            return;
        }
        txtDisplay2.setText("0");
    }//GEN-LAST:event_clearEntryBtnActionPerformed

    private void decimalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalBtnActionPerformed
        JLabel displayLabel = getEnabledDisplay();
        String currentText = getEnabledDisplay().getText();
        
        if (currentText.contains(".")) return; // If already contains . then return
        
        displayLabel.setText(currentText + ".");
    }//GEN-LAST:event_decimalBtnActionPerformed

    private void zeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtnActionPerformed
        displayLabel("0");
    }//GEN-LAST:event_zeroBtnActionPerformed

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
        displayLabel("1");
    }//GEN-LAST:event_oneBtnActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        displayLabel("2");
    }//GEN-LAST:event_twoBtnActionPerformed

    private void threeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtnActionPerformed
        displayLabel("3");
    }//GEN-LAST:event_threeBtnActionPerformed

    private void fourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtnActionPerformed
        displayLabel("4");
    }//GEN-LAST:event_fourBtnActionPerformed

    private void fiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtnActionPerformed
        displayLabel("5");
    }//GEN-LAST:event_fiveBtnActionPerformed

    private void sixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtnActionPerformed
        displayLabel("6");
    }//GEN-LAST:event_sixBtnActionPerformed

    private void sevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBtnActionPerformed
        displayLabel("7");
    }//GEN-LAST:event_sevenBtnActionPerformed

    private void eightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtnActionPerformed
        displayLabel("8");
    }//GEN-LAST:event_eightBtnActionPerformed

    private void nineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtnActionPerformed
        displayLabel("9");
    }//GEN-LAST:event_nineBtnActionPerformed

    private void txtDisplay1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDisplay1MouseClicked
       Font getLabelFont = txtDisplay1.getFont();
       if (getLabelFont.equals(semiboldFont)) return; // If label already selected, return;
       setEnabledDisplay(true);
    }//GEN-LAST:event_txtDisplay1MouseClicked

    private void txtDisplay2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDisplay2MouseClicked
        Font getLabelFont = txtDisplay2.getFont();
        if (getLabelFont.equals(semiboldFont)) return; // If label already selected, return;
        setEnabledDisplay(false);
    }//GEN-LAST:event_txtDisplay2MouseClicked
    
    private void setEnabledDisplay(boolean display){
        enabledDisplay = display; // If true, display1. else, display2
        if (enabledDisplay){
            txtDisplay1.setFont(semiboldFont);
            txtDisplay2.setFont(semilightFont);
        } else {
            txtDisplay2.setFont(semiboldFont);
            txtDisplay1.setFont(semilightFont);
        }
        updateConversion();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsLabel;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JButton backspaceBtn;
    private javax.swing.JButton clearEntryBtn;
    private javax.swing.JButton decimalBtn;
    private javax.swing.JButton eightBtn;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton fourBtn;
    private javax.swing.JButton nineBtn;
    private javax.swing.JButton oneBtn;
    private javax.swing.JButton sevenBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton twoBtn;
    private javax.swing.JLabel txtDisplay1;
    private javax.swing.JLabel txtDisplay2;
    private javax.swing.JComboBox<String> unitComboBox1;
    private javax.swing.JComboBox<String> unitComboBox2;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration//GEN-END:variables
}
