/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package advancedcalculatorpackage;

import java.awt.Font;
import java.awt.FontMetrics;
import java.text.DecimalFormat;
import javax.swing.JLabel;

/**
 *
 * @author seany
 */
public class TemperaturePanel extends javax.swing.JPanel {
    
    // For Display
    private final Font semiboldFont = new Font("Segoe UI Semibold", Font.PLAIN, 36);
    private final Font semilightFont = new Font("Segoe UI Semilight", Font.PLAIN, 36);
    
    // Limits
    private final int MAX_DIGIT_INPUT = 15;
    
    // For Conversion
    private final DecimalFormat decimalFormat = new DecimalFormat("#,##0.############");;
    
    // Tracks Active Display (true = display1, false = display2)
    private static boolean activeDisplay = true;
    
    /*
      Temperature units with conversion logic
    */
    private enum UnitOfTemperature{
        Celsius{
            @Override
            public double toCelsius(double value) {
                return value;
            }

            @Override
            public double fromCelsius(double celsiusValue) {
                return celsiusValue; 
            }
        },
        Fahrenheit{
            @Override
            public double toCelsius(double value) {
                return (value - 32) * 5.0/9.0;
            }

            @Override
            public double fromCelsius(double celsiusValue) {
                return celsiusValue * 9.0/5.0 + 32;
            }
        },
        Kelvin{
            @Override
            public double toCelsius(double value) {
                return value - 273.15;
            }

            @Override
            public double fromCelsius(double celsiusValue) {
                return celsiusValue + 273.15;
            }
        };
        
        public abstract double toCelsius(double value);
        public abstract double fromCelsius(double celsiusValue);
    };
    
    
    /**
     * Creates new form TimePanel
     */
    public TemperaturePanel() {
        initComponents();
        initLabelListeners();
        updateConversion();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayPanel = new javax.swing.JPanel();
        TemperatureLabel = new javax.swing.JLabel();
        txtDisplay2 = new javax.swing.JLabel();
        unitComboBox2 = new javax.swing.JComboBox<>();
        txtDisplay1 = new javax.swing.JLabel();
        unitComboBox1 = new javax.swing.JComboBox<>();
        ButtonsLabel = new javax.swing.JPanel();
        backspaceBtn = new javax.swing.JButton();
        clearEntryBtn = new javax.swing.JButton();
        eightBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        sevenBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        decimalBtn = new javax.swing.JButton();
        negateBtn = new javax.swing.JButton();
        fourBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        zeroBtn = new javax.swing.JButton();
        nineBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();
        oneBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(340, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DisplayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TemperatureLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        TemperatureLabel.setText("Temperature");
        TemperatureLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DisplayPanel.add(TemperatureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 35));

        txtDisplay2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        txtDisplay2.setText("0");
        txtDisplay2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDisplay2MouseClicked(evt);
            }
        });
        DisplayPanel.add(txtDisplay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        unitComboBox2.setMaximumRowCount(8);
        unitComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin" }));
        unitComboBox2.setSelectedIndex(1);
        unitComboBox2.setBorder(null);
        unitComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DisplayPanel.add(unitComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtDisplay1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        txtDisplay1.setText("0");
        txtDisplay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDisplay1MouseClicked(evt);
            }
        });
        DisplayPanel.add(txtDisplay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        unitComboBox1.setMaximumRowCount(8);
        unitComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin" }));
        unitComboBox1.setBorder(null);
        unitComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DisplayPanel.add(unitComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        add(DisplayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 240));

        ButtonsLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backspaceBtn.setBackground(new java.awt.Color(249, 249, 249));
        backspaceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/performancetasks/imgs/backspace.png"))); // NOI18N
        backspaceBtn.setFocusPainted(false);
        backspaceBtn.setFocusable(false);
        backspaceBtn.setRequestFocusEnabled(false);
        backspaceBtn.setRolloverEnabled(false);
        backspaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(backspaceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 0, 80, 50));

        clearEntryBtn.setBackground(new java.awt.Color(249, 249, 249));
        clearEntryBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearEntryBtn.setText("CE");
        clearEntryBtn.setFocusPainted(false);
        clearEntryBtn.setFocusable(false);
        clearEntryBtn.setRequestFocusEnabled(false);
        clearEntryBtn.setRolloverEnabled(false);
        clearEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEntryBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(clearEntryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 50, 80, 50));

        eightBtn.setBackground(new java.awt.Color(249, 249, 249));
        eightBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eightBtn.setText("8");
        eightBtn.setFocusPainted(false);
        eightBtn.setFocusable(false);
        eightBtn.setRequestFocusEnabled(false);
        eightBtn.setRolloverEnabled(false);
        eightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(eightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 0, 80, 50));

        fiveBtn.setBackground(new java.awt.Color(249, 249, 249));
        fiveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fiveBtn.setText("5");
        fiveBtn.setFocusPainted(false);
        fiveBtn.setFocusable(false);
        fiveBtn.setRequestFocusEnabled(false);
        fiveBtn.setRolloverEnabled(false);
        fiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(fiveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 50, 80, 50));

        sevenBtn.setBackground(new java.awt.Color(249, 249, 249));
        sevenBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sevenBtn.setText("7");
        sevenBtn.setFocusPainted(false);
        sevenBtn.setFocusable(false);
        sevenBtn.setRequestFocusEnabled(false);
        sevenBtn.setRolloverEnabled(false);
        sevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(sevenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 80, 50));

        threeBtn.setBackground(new java.awt.Color(249, 249, 249));
        threeBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        threeBtn.setText("3");
        threeBtn.setFocusPainted(false);
        threeBtn.setFocusable(false);
        threeBtn.setRequestFocusEnabled(false);
        threeBtn.setRolloverEnabled(false);
        threeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(threeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 100, 80, 50));

        decimalBtn.setBackground(new java.awt.Color(249, 249, 249));
        decimalBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        decimalBtn.setText(".");
        decimalBtn.setFocusPainted(false);
        decimalBtn.setFocusable(false);
        decimalBtn.setRequestFocusEnabled(false);
        decimalBtn.setRolloverEnabled(false);
        decimalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(decimalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 150, 80, 50));

        negateBtn.setBackground(new java.awt.Color(249, 249, 249));
        negateBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        negateBtn.setText("+/-");
        negateBtn.setFocusPainted(false);
        negateBtn.setFocusable(false);
        negateBtn.setRequestFocusEnabled(false);
        negateBtn.setRolloverEnabled(false);
        negateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negateBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(negateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 150, 80, 50));

        fourBtn.setBackground(new java.awt.Color(249, 249, 249));
        fourBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fourBtn.setText("4");
        fourBtn.setFocusPainted(false);
        fourBtn.setFocusable(false);
        fourBtn.setRequestFocusEnabled(false);
        fourBtn.setRolloverEnabled(false);
        fourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(fourBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 50, 80, 50));

        twoBtn.setBackground(new java.awt.Color(249, 249, 249));
        twoBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        twoBtn.setText("2");
        twoBtn.setFocusPainted(false);
        twoBtn.setFocusable(false);
        twoBtn.setRequestFocusEnabled(false);
        twoBtn.setRolloverEnabled(false);
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(twoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 100, 80, 50));

        zeroBtn.setBackground(new java.awt.Color(249, 249, 249));
        zeroBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        zeroBtn.setText("0");
        zeroBtn.setFocusPainted(false);
        zeroBtn.setFocusable(false);
        zeroBtn.setRequestFocusEnabled(false);
        zeroBtn.setRolloverEnabled(false);
        zeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(zeroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 150, 80, 50));

        nineBtn.setBackground(new java.awt.Color(249, 249, 249));
        nineBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nineBtn.setText("9");
        nineBtn.setFocusPainted(false);
        nineBtn.setFocusable(false);
        nineBtn.setRequestFocusEnabled(false);
        nineBtn.setRolloverEnabled(false);
        nineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(nineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 0, 80, 50));

        sixBtn.setBackground(new java.awt.Color(249, 249, 249));
        sixBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sixBtn.setText("6");
        sixBtn.setFocusPainted(false);
        sixBtn.setFocusable(false);
        sixBtn.setRequestFocusEnabled(false);
        sixBtn.setRolloverEnabled(false);
        sixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(sixBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 50, 80, 50));

        oneBtn.setBackground(new java.awt.Color(249, 249, 249));
        oneBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        oneBtn.setText("1");
        oneBtn.setFocusPainted(false);
        oneBtn.setFocusable(false);
        oneBtn.setRequestFocusEnabled(false);
        oneBtn.setRolloverEnabled(false);
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });
        ButtonsLabel.add(oneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 100, 80, 50));

        add(ButtonsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 340, 210));
    }// </editor-fold>//GEN-END:initComponents

    /*
        Initialize event listeners for unit combo boxes
    */
    private void initLabelListeners(){
        unitComboBox1.addActionListener(e -> updateConversion());
        unitComboBox2.addActionListener(e -> updateConversion());
    }
    
    /*
        Convert temperature between units
    */
    private double convert(double value, UnitOfTemperature unitFrom, UnitOfTemperature unitTo) {
        double celsius = unitFrom.toCelsius(value);
        return unitTo.fromCelsius(celsius);
    }
    
    /*
        Format numbers with commas and remove unnecessary decimals
    */
    private String formatNumber(double value){
        String formatted = decimalFormat.format(value);
        
        // If it is a whole number, return without decimals
        if (value == Math.floor(value) && !Double.isInfinite(value)) {
            return String.format("%,d", (long) value);
        }
        
        return formatted;
    }
    
    /*
        Parses number string 
    */
    private double parseDisplay() {
        try {
            // Removes commas before parsing
            String text = getActiveDisplay().getText().replace(",", "");
            return Double.parseDouble(text);
        } catch (NumberFormatException e) {
            return 0;
        }
    }
    
    /*
        Get current active display
    */
    private JLabel getActiveDisplay(){
        return activeDisplay ? txtDisplay1 : txtDisplay2;
    }
    
    /*
        Get inactive display
    */
    private JLabel getInactiveDisplay(){
        return activeDisplay ? txtDisplay2 : txtDisplay1;
    }
    
    /*
        Get unit for active display
    */
    private UnitOfTemperature getActiveUnit(){
        int index = activeDisplay ? unitComboBox1.getSelectedIndex() : unitComboBox2.getSelectedIndex();
        return UnitOfTemperature.values()[index];
    }
    
    /*
        Get unit for inactive display
    */
    private UnitOfTemperature getInactiveUnit(){
        int index = activeDisplay ? unitComboBox2.getSelectedIndex() : unitComboBox1.getSelectedIndex();
        return UnitOfTemperature.values()[index];
    }
    
    /*
        Updates conversion and displays result
    */
    private void updateConversion(){
        double num = parseDisplay();
        double result = convert(num, getActiveUnit(), getInactiveUnit());
        getInactiveDisplay().setText(formatNumber(result));
        resizeLabel(getInactiveDisplay());
    }
    
    /*
        Format active label and update conversion
    */
    private void formatAndUpdate() {
        JLabel currentDisplay = getActiveDisplay();
        String currentText = currentDisplay.getText().replace(",", "");
        
        if (!currentText.contains(".") && !currentText.isEmpty()) {
            currentDisplay.setText(formatNumber(parseDisplay()));
	}
        resizeLabel(getActiveDisplay());
        resizeLabel(getInactiveDisplay());
        updateConversion();
    }
    
    /*
        Append number to active display
    */
    private void appendNumber(String number) {
        JLabel currentDisplay = getActiveDisplay();
        String currentText = currentDisplay.getText().replace(",", "");
        
        if (currentText.equals("0")) {
            currentDisplay.setText(number);
            formatAndUpdate();
            return;
        
        }
        
        // Checks text length without thousand separator, decimal, and minus
        String textWithoutFormat = currentText.replace(".", "").replace("-", "");
        
        if (textWithoutFormat.length() >= MAX_DIGIT_INPUT) {
            return;
        }
        
        if (currentText.contains(".") || !currentText.equals("0")) {
            currentDisplay.setText(currentText + number);
            formatAndUpdate();
        }
    }
    
    private void backspaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceBtnActionPerformed
        JLabel currentDisplay = getActiveDisplay();
        String currentText = currentDisplay.getText().replace(",", "");
        
        if (currentText.length() > 1) {
            String newText = currentText.substring(0, currentText.length() -1);
            currentDisplay.setText(newText);
        } else {
            
            currentDisplay.setText("0");
        }
        formatAndUpdate();
    }//GEN-LAST:event_backspaceBtnActionPerformed
    
    private void clearEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearEntryBtnActionPerformed
        getActiveDisplay().setText("0");
        resetFontSize(getActiveDisplay());
        formatAndUpdate();
    }//GEN-LAST:event_clearEntryBtnActionPerformed

    private void decimalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalBtnActionPerformed
        JLabel currentDisplay = getActiveDisplay();
        String currentText = currentDisplay.getText().replace(",", "");
         
        if (currentText.contains(".")) return;
        
        currentDisplay.setText(currentText + ".");
        resizeLabel(currentDisplay);
        updateConversion();
    }//GEN-LAST:event_decimalBtnActionPerformed

    private void zeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtnActionPerformed
        appendNumber("0");
    }//GEN-LAST:event_zeroBtnActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        appendNumber("2");
    }//GEN-LAST:event_twoBtnActionPerformed

    private void threeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtnActionPerformed
        appendNumber("3");
    }//GEN-LAST:event_threeBtnActionPerformed

    private void fourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtnActionPerformed
        appendNumber("4");
    }//GEN-LAST:event_fourBtnActionPerformed

    private void fiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtnActionPerformed
        appendNumber("5");
    }//GEN-LAST:event_fiveBtnActionPerformed

    private void sixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtnActionPerformed
        appendNumber("6");
    }//GEN-LAST:event_sixBtnActionPerformed

    private void sevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBtnActionPerformed
        appendNumber("7");
    }//GEN-LAST:event_sevenBtnActionPerformed

    private void eightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtnActionPerformed
        appendNumber("8");
    }//GEN-LAST:event_eightBtnActionPerformed

    private void nineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtnActionPerformed
        appendNumber("9");
    }//GEN-LAST:event_nineBtnActionPerformed

    private void txtDisplay1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDisplay1MouseClicked
        setActiveDisplay(true);
    }//GEN-LAST:event_txtDisplay1MouseClicked

    private void txtDisplay2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDisplay2MouseClicked
        setActiveDisplay(false);
    }//GEN-LAST:event_txtDisplay2MouseClicked

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
        appendNumber("1");
    }//GEN-LAST:event_oneBtnActionPerformed

    private void negateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negateBtnActionPerformed
        JLabel currentDisplay = getActiveDisplay();
        String currentText = currentDisplay.getText();
        
        if (currentText.startsWith("-")) {
            String newText = currentText.substring(1);
            currentDisplay.setText(newText);

            if (newText.endsWith(".")) {
                resizeLabel(currentDisplay);
                updateConversion();
            } else {
                formatAndUpdate();
            }
            return;
        }
        
        if (currentText.equals("0")) {
            currentDisplay.setText("-" + currentText);
            return;
        }
        
        if (currentText.endsWith(".")) {
            currentDisplay.setText("-" + currentText);
            resizeLabel(currentDisplay);
            updateConversion();
            return;
        }

        // Handle regular numbers
        double num = parseDisplay();
        num *= -1;
        currentDisplay.setText(formatNumber(num));
        formatAndUpdate();
    }//GEN-LAST:event_negateBtnActionPerformed
    
    /*
        Set which display is active
    */
    private void setActiveDisplay(boolean display1){
        if (activeDisplay == display1) return;
        
        activeDisplay = display1;
        
        if (activeDisplay){
            txtDisplay1.setFont(semiboldFont);
            txtDisplay2.setFont(semilightFont);
        } else {
            txtDisplay2.setFont(semiboldFont);
            txtDisplay1.setFont(semilightFont);
        }
        resizeLabel(getActiveDisplay());
        resizeLabel(getInactiveDisplay());
        updateConversion();
    }
    
    private void resizeLabel(JLabel label){
        String text = label.getText();
        if (text.isEmpty()) return;

        int maxWidth = 320; // Maximum width for the label
        int fontSize = 36; // Default Font Size
        Font font = label.getFont().deriveFont((float) fontSize);
        FontMetrics metrics = label.getFontMetrics(font);
        int textWidth = metrics.stringWidth(text);

        // If text fits at full size, set label width to text width
        if (textWidth <= maxWidth) {
            label.setSize(textWidth, label.getHeight());
            label.setFont(font);
        } else {
            // Text doesn't fit, shrink font until it fits in maxWidth
            label.setSize(maxWidth, label.getHeight());

            while (metrics.stringWidth(text) > maxWidth && fontSize > 8) {
                fontSize -= 1;
                font = label.getFont().deriveFont((float) fontSize);
                metrics = label.getFontMetrics(font);
            }
            label.setFont(font);
        }
    }
    
    private void resetFontSize(JLabel label) {
        Font font = label.getFont().deriveFont(36f);
        label.setFont(font);
        // Reset label to appropriate width
        FontMetrics metrics = label.getFontMetrics(font);
        String text = label.getText();
        int textWidth = metrics.stringWidth(text);
        int maxWidth = 320;

        if (textWidth <= maxWidth) {
            label.setSize(textWidth, label.getHeight());
        } else {
            label.setSize(maxWidth, label.getHeight());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsLabel;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JLabel TemperatureLabel;
    private javax.swing.JButton backspaceBtn;
    private javax.swing.JButton clearEntryBtn;
    private javax.swing.JButton decimalBtn;
    private javax.swing.JButton eightBtn;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton fourBtn;
    private javax.swing.JButton negateBtn;
    private javax.swing.JButton nineBtn;
    private javax.swing.JButton oneBtn;
    private javax.swing.JButton sevenBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton twoBtn;
    private javax.swing.JLabel txtDisplay1;
    private javax.swing.JLabel txtDisplay2;
    private javax.swing.JComboBox<String> unitComboBox1;
    private javax.swing.JComboBox<String> unitComboBox2;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration//GEN-END:variables
}
