/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javacomponents_part1;

import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author ihub27
 */
public class StudentForm extends javax.swing.JFrame {
    private final List<javax.swing.JCheckBox> checkboxes;
    /**
     * Creates new form StudentForm
     */
    public StudentForm() {
        initComponents();
        checkboxes = new ArrayList<>();
        
        checkboxes.add(Math); checkboxes.add(English); checkboxes.add(Science);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nameLabel = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        Math = new javax.swing.JCheckBox();
        English = new javax.swing.JCheckBox();
        Science = new javax.swing.JCheckBox();
        favoriteSubjectsLabel = new javax.swing.JLabel();
        Enrolled = new javax.swing.JRadioButton();
        notEnrolled = new javax.swing.JRadioButton();
        statusLabel = new javax.swing.JLabel();
        zodiacSignLabel = new javax.swing.JLabel();
        zodiacSignComboBox = new javax.swing.JComboBox<>();
        saveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentData = new javax.swing.JTextArea();
        clearBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Form");
        setName("Student Form"); // NOI18N
        setResizable(false);

        nameLabel.setText("Name");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        Math.setText("Math");
        Math.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MathActionPerformed(evt);
            }
        });

        English.setText("English");
        English.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnglishActionPerformed(evt);
            }
        });

        Science.setText("Science");

        favoriteSubjectsLabel.setText("Favorite Subject/s");

        buttonGroup1.add(Enrolled);
        Enrolled.setText("Enrolled");
        Enrolled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrolledActionPerformed(evt);
            }
        });

        buttonGroup1.add(notEnrolled);
        notEnrolled.setText("Not Enrolled");

        statusLabel.setText("Status");

        zodiacSignLabel.setText("Zodiac Sign");

        zodiacSignComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "Capricorn", "Aquarius ", "Pisces", "Aries", "Taurus", "Gemini", "Cancer", "Leo,", "Virgo", "Libra", "Scorpio", "Sagittarius" }));
        zodiacSignComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zodiacSignComboBoxActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        studentData.setEditable(false);
        studentData.setColumns(20);
        studentData.setRows(5);
        jScrollPane1.setViewportView(studentData);

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(favoriteSubjectsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(Math)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(English)
                        .addGap(12, 12, 12)
                        .addComponent(Science))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusLabel)
                            .addComponent(nameLabel)
                            .addComponent(zodiacSignLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(zodiacSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Enrolled)
                                        .addGap(18, 18, 18)
                                        .addComponent(notEnrolled)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(saveBtn)
                .addGap(18, 18, 18)
                .addComponent(clearBtn)
                .addGap(18, 18, 18)
                .addComponent(cancelBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Math)
                            .addComponent(favoriteSubjectsLabel)
                            .addComponent(English)
                            .addComponent(Science))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusLabel)
                            .addComponent(Enrolled)
                            .addComponent(notEnrolled))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zodiacSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zodiacSignLabel)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(clearBtn)
                    .addComponent(cancelBtn))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    private void displaySelectedSubjects() {
//        StringBuilder selectedText = new StringBuilder("\nFavorite Subject/s: ");
//        for (javax.swing.JCheckBox checkbox : checkboxes) {
//            if (checkbox.isSelected()) selectedText.append(checkbox.getText()+" ");
//        }
//        studentData.append(selectedText.toString());
//    }
    private boolean displaySelectedSubjects() {
        boolean anySelected = false;
        for (javax.swing.JCheckBox checkBox : checkboxes) {
            if (checkBox.isSelected()) {
                anySelected = true;
                //selectedSubjects.append(checkBox.getText()).append(" ");
            }
        }
        return anySelected;
    }
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
            
        }

        return null;
    }
    private void MathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MathActionPerformed
        
    }//GEN-LAST:event_MathActionPerformed

    private void zodiacSignComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zodiacSignComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zodiacSignComboBoxActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        studentData.setText("");
        
        String name = txtName.getText();
        int sign = zodiacSignComboBox.getSelectedIndex();
        boolean isChecked = displaySelectedSubjects();
        System.out.println(isChecked);
        if (name.isBlank() && isChecked &&
            buttonGroup1.getSelection() == null && sign == 0){ 
            studentData.setText("");
            JOptionPane.showMessageDialog(
            StudentForm.this,
            "Please fill in all required fields.",
            "Input Error!",
            JOptionPane.ERROR_MESSAGE);
        } else if (name.isBlank() || !isChecked || buttonGroup1.getSelection() == null || sign == 0) {
            studentData.setText("");
            JOptionPane.showMessageDialog(
            StudentForm.this,
            "Please fill in all required fields.",
            "Input Error!",
            JOptionPane.ERROR_MESSAGE);
        } else {
            studentData.append("Name: "+ txtName.getText());
            studentData.append("\nFavorite Subject/s: ");
            for (javax.swing.JCheckBox checkbox : checkboxes) {
                if (checkbox.isSelected())
                studentData.append(checkbox.getText()+" ");
            }
            studentData.append("\nStatus: "+getSelectedButtonText(buttonGroup1));
            studentData.append("\nZodiac Sign: "+zodiacSignComboBox.getSelectedItem().toString());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void EnrolledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrolledActionPerformed

    }//GEN-LAST:event_EnrolledActionPerformed

    private void EnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnglishActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        Math.setSelected(false); English.setSelected(false); Science.setSelected(false);
        buttonGroup1.clearSelection();
        zodiacSignComboBox.setSelectedIndex(0);
        studentData.setText("");
        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox English;
    private javax.swing.JRadioButton Enrolled;
    private javax.swing.JCheckBox Math;
    private javax.swing.JCheckBox Science;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel favoriteSubjectsLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JRadioButton notEnrolled;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextArea studentData;
    private javax.swing.JTextField txtName;
    private javax.swing.JComboBox<String> zodiacSignComboBox;
    private javax.swing.JLabel zodiacSignLabel;
    // End of variables declaration//GEN-END:variables
}
