/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javacomponents_part1;

/**
 *
 * @author ihub27
 */
public class StudentForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentForm
     */
    public StudentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fullNameLabel = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        Math = new javax.swing.JCheckBox();
        English = new javax.swing.JCheckBox();
        Science = new javax.swing.JCheckBox();
        favoriteSubjectsLabel = new javax.swing.JLabel();
        Enrolled = new javax.swing.JRadioButton();
        notEnrolled = new javax.swing.JRadioButton();
        statusLabel = new javax.swing.JLabel();
        zodiacSignLabel = new javax.swing.JLabel();
        zodiacSignComboBox = new javax.swing.JComboBox<>();
        saveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentData = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Student Form"); // NOI18N
        setResizable(false);

        fullNameLabel.setText("Full Name");

        Math.setText("Math");
        Math.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MathActionPerformed(evt);
            }
        });

        English.setText("English");
        English.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnglishActionPerformed(evt);
            }
        });

        Science.setText("Science");

        favoriteSubjectsLabel.setText("Favorite Subject/s");

        buttonGroup1.add(Enrolled);
        Enrolled.setText("Enrolled");
        Enrolled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrolledActionPerformed(evt);
            }
        });

        buttonGroup1.add(notEnrolled);
        notEnrolled.setText("Not Enrolled");

        statusLabel.setText("Status");

        zodiacSignLabel.setText("Zodiac Sign");

        zodiacSignComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "Capricorn", "Aquarius ", "Pisces", "Aries", "Taurus", "Gemini", "Cancer", "Leo,", "Virgo", "Libra", "Scorpio", "Sagittarius" }));
        zodiacSignComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zodiacSignComboBoxActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        studentData.setEditable(false);
        studentData.setColumns(20);
        studentData.setRows(5);
        jScrollPane1.setViewportView(studentData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(saveBtn)
                .addGap(234, 234, 234))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fullNameLabel)
                        .addGap(52, 52, 52)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(favoriteSubjectsLabel)
                                .addGap(12, 12, 12)
                                .addComponent(Math)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(English)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Science))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(statusLabel)
                                .addGap(74, 74, 74)
                                .addComponent(Enrolled)
                                .addGap(18, 18, 18)
                                .addComponent(notEnrolled))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(zodiacSignLabel)
                                .addGap(44, 44, 44)
                                .addComponent(zodiacSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fullNameLabel)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Math)
                            .addComponent(favoriteSubjectsLabel)
                            .addComponent(English)
                            .addComponent(Science))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusLabel)
                            .addComponent(Enrolled)
                            .addComponent(notEnrolled))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zodiacSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zodiacSignLabel)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MathActionPerformed
        studentData.append("Favorite Subjects: ");
    }//GEN-LAST:event_MathActionPerformed

    private void zodiacSignComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zodiacSignComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zodiacSignComboBoxActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        studentData.setText("");
        
        studentData.append("Name: "+ txtFirstName.getText());
        
        if (Math.isSelected() || English.isSelected()|| Science.isSelected()){
            studentData.append("\nFavorite Subject\s: ");
            if (Math.isSelected()){
                studentData.append(Math.getText()+ "\n");
            } if (English.isSelected()){
                studentData.append("\n" + English.getText()+ "\n");
            } if (Science.isSelected()){
                studentData.append("\n" + Science.getText()+ "\n");
            }
        }
        
        if(Enrolled.isSelected()){
            studentData.append("\nStatus: " + Enrolled.getText());
        } if(notEnrolled.isSelected()) {
            studentData.append("\nStatus: " + notEnrolled.getText());
        }
        studentData.append("\nZodiac Sign: " + zodiacSignComboBox.getSelectedItem().toString());
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void EnrolledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrolledActionPerformed

    }//GEN-LAST:event_EnrolledActionPerformed

    private void EnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnglishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox English;
    private javax.swing.JRadioButton Enrolled;
    private javax.swing.JCheckBox Math;
    private javax.swing.JCheckBox Science;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel favoriteSubjectsLabel;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton notEnrolled;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextArea studentData;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JComboBox<String> zodiacSignComboBox;
    private javax.swing.JLabel zodiacSignLabel;
    // End of variables declaration//GEN-END:variables
}
