/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package performancetasks;

import javax.swing.JOptionPane;
import javacomponents_part1_activities.*;
/**
 *
 * @author ihub27
 */
public class ApplicationsMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuOfProjects
     */
    public ApplicationsMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        gradecalculatorBtn = new javax.swing.JButton();
        payrollsystemBtn = new javax.swing.JButton();
        studentregformBtn = new javax.swing.JButton();
        temperatureconverterBtn = new javax.swing.JButton();
        studentformBtn = new javax.swing.JButton();
        numberFormattingApp = new javax.swing.JButton();
        openingClosingWindowBtn = new javax.swing.JButton();
        javaParsingBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nextpageBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Application Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(530, 290));
        setMinimumSize(new java.awt.Dimension(530, 290));
        setPreferredSize(new java.awt.Dimension(530, 310));
        setResizable(false);
        setSize(new java.awt.Dimension(530, 310));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Applications Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        gradecalculatorBtn.setText("Grade Calculator App");
        gradecalculatorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradecalculatorBtnActionPerformed(evt);
            }
        });
        getContentPane().add(gradecalculatorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 210, -1));

        payrollsystemBtn.setText("Simple Payroll System App");
        payrollsystemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payrollsystemBtnActionPerformed(evt);
            }
        });
        getContentPane().add(payrollsystemBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 210, -1));

        studentregformBtn.setText("Student Registration Form App");
        studentregformBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentregformBtnActionPerformed(evt);
            }
        });
        getContentPane().add(studentregformBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 210, -1));

        temperatureconverterBtn.setText("Temperature Converter App");
        temperatureconverterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureconverterBtnActionPerformed(evt);
            }
        });
        getContentPane().add(temperatureconverterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 210, -1));

        studentformBtn.setText("Student Form App");
        studentformBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentformBtnActionPerformed(evt);
            }
        });
        getContentPane().add(studentformBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 210, -1));

        numberFormattingApp.setText("Number Formatting App");
        numberFormattingApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberFormattingAppActionPerformed(evt);
            }
        });
        getContentPane().add(numberFormattingApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 210, -1));

        openingClosingWindowBtn.setText("Opening Closing Window App");
        openingClosingWindowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openingClosingWindowBtnActionPerformed(evt);
            }
        });
        getContentPane().add(openingClosingWindowBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 210, -1));

        javaParsingBtn.setText("Java Parsing App");
        javaParsingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javaParsingBtnActionPerformed(evt);
            }
        });
        getContentPane().add(javaParsingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 210, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Performance Tasks");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 50, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Activities");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        nextpageBtn.setText(">>");
        nextpageBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nextpageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextpageBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nextpageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 49, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to close the application?", "Message", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing
    
    
    
    private void gradecalculatorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradecalculatorBtnActionPerformed
        pt_gradecalculator gradeCalculator = new pt_gradecalculator();
        gradeCalculator.setLocationRelativeTo(this);
        gradeCalculator.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gradecalculatorBtnActionPerformed

    private void payrollsystemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payrollsystemBtnActionPerformed
        pt_simplepayrollsystem payrollSystem = new pt_simplepayrollsystem();
        payrollSystem.setLocationRelativeTo(this);
        payrollSystem.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_payrollsystemBtnActionPerformed

    private void studentregformBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentregformBtnActionPerformed
        pt_studentregform studentRegForm = new pt_studentregform();
        studentRegForm.setLocationRelativeTo(this);
        studentRegForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studentregformBtnActionPerformed

    private void temperatureconverterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureconverterBtnActionPerformed
        pt_temperatureconverter tempConverter = new pt_temperatureconverter();
        tempConverter.setLocationRelativeTo(this);
        tempConverter.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_temperatureconverterBtnActionPerformed

    private void studentformBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentformBtnActionPerformed
        StudentForm studentForm = new StudentForm();
        studentForm.setLocationRelativeTo(this);
        studentForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studentformBtnActionPerformed

    private void numberFormattingAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberFormattingAppActionPerformed
        NumberFormatting numberFormatting = new NumberFormatting();
        numberFormatting.setLocationRelativeTo(this);
        numberFormatting.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_numberFormattingAppActionPerformed

    private void openingClosingWindowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openingClosingWindowBtnActionPerformed
        OpeningClosingWindow openingClosingWindow = new OpeningClosingWindow();
        openingClosingWindow.setLocationRelativeTo(this);
        openingClosingWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_openingClosingWindowBtnActionPerformed

    private void javaParsingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaParsingBtnActionPerformed
        JavaParsing javaParsing = new JavaParsing();
        javaParsing.setLocationRelativeTo(this);
        javaParsing.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_javaParsingBtnActionPerformed

    private void nextpageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextpageBtnActionPerformed
//        for (java.awt.Component comp : this.getComponents()) {
//            if (comp != null && comp !=)
//        }
    }//GEN-LAST:event_nextpageBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationsMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gradecalculatorBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton javaParsingBtn;
    private javax.swing.JButton nextpageBtn;
    private javax.swing.JButton numberFormattingApp;
    private javax.swing.JButton openingClosingWindowBtn;
    private javax.swing.JButton payrollsystemBtn;
    private javax.swing.JButton studentformBtn;
    private javax.swing.JButton studentregformBtn;
    private javax.swing.JButton temperatureconverterBtn;
    // End of variables declaration//GEN-END:variables
}
