/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package performancetasks;

import javacomponents_part1_activities.SimpleCalculator;

/**
 *
 * @author ihub27
 */
public class ApplicationMenuSecondPage extends javax.swing.JPanel {
    /**
     * Creates new form ApplicationMenuSecondPanel
     */
    public ApplicationMenuSecondPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SecondPagePanel = new javax.swing.JPanel();
        PreviousPageButton = new javax.swing.JButton();
        SimpleCalcButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(575, 360));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SecondPagePanel.setPreferredSize(new java.awt.Dimension(575, 360));
        SecondPagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PreviousPageButton.setText("<<");
        PreviousPageButton.setActionCommand("<<");
        PreviousPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousPageButtonActionPerformed(evt);
            }
        });
        SecondPagePanel.add(PreviousPageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 90, 30));

        SimpleCalcButton.setText("Simple Calculator");
        SimpleCalcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpleCalcButtonActionPerformed(evt);
            }
        });
        SecondPagePanel.add(SimpleCalcButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 110, 172, -1));

        add(SecondPagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 575, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void SimpleCalcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpleCalcButtonActionPerformed
        SimpleCalculator simpCalc = new SimpleCalculator();
        simpCalc.setLocationRelativeTo(this);
        simpCalc.setVisible(true);
        ApplicationMenu appMenu = new ApplicationMenu();
        appMenu.dispose();
    }//GEN-LAST:event_SimpleCalcButtonActionPerformed

    private void PreviousPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousPageButtonActionPerformed
        for(java.awt.Component comp : SecondPagePanel.getComponents()){
            if(comp == PreviousPageButton && comp == SimpleCalcButton) {
                SecondPagePanel.remove(comp);
            }
        }
        SecondPagePanel.add(new ApplicationMenuFirstPage(), new org.netbeans.lib.awtextra.AbsoluteConstraints
        (0, 0, SecondPagePanel.getWidth(), SecondPagePanel.getHeight()));
        
        SecondPagePanel.revalidate();
        SecondPagePanel.repaint();
    }//GEN-LAST:event_PreviousPageButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PreviousPageButton;
    private javax.swing.JPanel SecondPagePanel;
    private javax.swing.JButton SimpleCalcButton;
    // End of variables declaration//GEN-END:variables
}
