/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package performancetasks;

import javacomponents_part1_activities.*;
/**
 *
 * @author ihub27
 */
public class ApplicationMenuFirstPage extends javax.swing.JPanel {
    /**
     * Creates new form ApplicationMenuFirstPage
     */
    public ApplicationMenuFirstPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        NextPageButton = new javax.swing.JButton();
        TempConverterButton = new javax.swing.JButton();
        GradeCalcButton = new javax.swing.JButton();
        SimpPayrollSystemButton = new javax.swing.JButton();
        StudentRegFormButton = new javax.swing.JButton();
        JavaParsingButton = new javax.swing.JButton();
        OpeningClosingWindowButton = new javax.swing.JButton();
        NumberFormattingButton = new javax.swing.JButton();
        StudentFormButton = new javax.swing.JButton();
        PerformanceLabel = new javax.swing.JLabel();
        MainLabel = new javax.swing.JLabel();
        ActivitiesLabel = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(527, 340));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setMinimumSize(new java.awt.Dimension(575, 395));
        MainPanel.setOpaque(false);
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NextPageButton.setText(">>");
        NextPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextPageButtonActionPerformed(evt);
            }
        });
        MainPanel.add(NextPageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 90, 30));

        TempConverterButton.setText("Temperature Converter");
        TempConverterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempConverterButtonActionPerformed(evt);
            }
        });
        MainPanel.add(TempConverterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 172, -1));

        GradeCalcButton.setText("Grade Calculator");
        GradeCalcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeCalcButtonActionPerformed(evt);
            }
        });
        MainPanel.add(GradeCalcButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 172, -1));

        SimpPayrollSystemButton.setText("Simple Payroll System");
        SimpPayrollSystemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpPayrollSystemButtonActionPerformed(evt);
            }
        });
        MainPanel.add(SimpPayrollSystemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 172, -1));

        StudentRegFormButton.setText("Student Registration Form");
        StudentRegFormButton.setToolTipText("");
        StudentRegFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentRegFormButtonActionPerformed(evt);
            }
        });
        MainPanel.add(StudentRegFormButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        JavaParsingButton.setText("Java Parsing App");
        JavaParsingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JavaParsingButtonActionPerformed(evt);
            }
        });
        MainPanel.add(JavaParsingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 260, 172, -1));

        OpeningClosingWindowButton.setText("Opening Closing Window");
        OpeningClosingWindowButton.setToolTipText("");
        OpeningClosingWindowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpeningClosingWindowButtonActionPerformed(evt);
            }
        });
        MainPanel.add(OpeningClosingWindowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 210, 172, -1));

        NumberFormattingButton.setText("Number Formatting");
        NumberFormattingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberFormattingButtonActionPerformed(evt);
            }
        });
        MainPanel.add(NumberFormattingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 160, 172, -1));

        StudentFormButton.setText("Student Form");
        StudentFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentFormButtonActionPerformed(evt);
            }
        });
        MainPanel.add(StudentFormButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 110, 172, -1));

        PerformanceLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        PerformanceLabel.setText("Performance Tasks");
        MainPanel.add(PerformanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        MainLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        MainLabel.setText("Application Menu");
        MainPanel.add(MainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 20, -1, -1));

        ActivitiesLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ActivitiesLabel.setText("Activities");
        MainPanel.add(ActivitiesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jPanel1.add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NextPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextPageButtonActionPerformed
        changePanelTo(new ApplicationMenuSecondPage());
    }//GEN-LAST:event_NextPageButtonActionPerformed

    private void TempConverterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempConverterButtonActionPerformed
        pt_temperatureconverter tempConverter = new pt_temperatureconverter();
        tempConverter.setLocationRelativeTo(this);
        tempConverter.setVisible(true);
        ApplicationMenu appMenu = new ApplicationMenu();
        appMenu.dispose();
    }//GEN-LAST:event_TempConverterButtonActionPerformed

    private void GradeCalcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeCalcButtonActionPerformed
        pt_gradecalculator gradeCalculator = new pt_gradecalculator();
        gradeCalculator.setLocationRelativeTo(this);
        gradeCalculator.setVisible(true);
        ApplicationMenu appMenu = new ApplicationMenu();
        appMenu.dispose();
    }//GEN-LAST:event_GradeCalcButtonActionPerformed

    private void SimpPayrollSystemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpPayrollSystemButtonActionPerformed
        pt_simplepayrollsystem payrollSystem = new pt_simplepayrollsystem();
        payrollSystem.setLocationRelativeTo(this);
        payrollSystem.setVisible(true);
        ApplicationMenu appMenu = new ApplicationMenu();
        appMenu.dispose();
    }//GEN-LAST:event_SimpPayrollSystemButtonActionPerformed

    private void StudentRegFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentRegFormButtonActionPerformed
        pt_studentregform studentRegForm = new pt_studentregform();
        studentRegForm.setLocationRelativeTo(this);
        studentRegForm.setVisible(true);
        ApplicationMenu appMenu = new ApplicationMenu();
        appMenu.dispose();
    }//GEN-LAST:event_StudentRegFormButtonActionPerformed

    private void JavaParsingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JavaParsingButtonActionPerformed
        JavaParsing javaParsing = new JavaParsing();
        javaParsing.setLocationRelativeTo(this);
        javaParsing.setVisible(true);
        ApplicationMenu appMenu = new ApplicationMenu();
        appMenu.dispose();
    }//GEN-LAST:event_JavaParsingButtonActionPerformed

    private void OpeningClosingWindowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpeningClosingWindowButtonActionPerformed
        OpeningClosingWindow openingClosingWindow = new OpeningClosingWindow();
        openingClosingWindow.setLocationRelativeTo(this);
        openingClosingWindow.setVisible(true);
        ApplicationMenu appMenu = new ApplicationMenu();
        appMenu.dispose();
    }//GEN-LAST:event_OpeningClosingWindowButtonActionPerformed

    private void NumberFormattingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberFormattingButtonActionPerformed
        NumberFormatting numberFormatting = new NumberFormatting();
        numberFormatting.setLocationRelativeTo(this);
        numberFormatting.setVisible(true);
        ApplicationMenu appMenu = new ApplicationMenu();
        appMenu.dispose();
    }//GEN-LAST:event_NumberFormattingButtonActionPerformed

    private void StudentFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentFormButtonActionPerformed
        StudentForm studentForm = new StudentForm();
        studentForm.setLocationRelativeTo(this);
        studentForm.setVisible(true);
        ApplicationMenu appMenu = new ApplicationMenu();
        appMenu.dispose();
    }//GEN-LAST:event_StudentFormButtonActionPerformed
    
    private void changePanelTo (javax.swing.JPanel newPanel) {
        for(java.awt.Component comp : MainPanel.getComponents()){
            if(comp != null && comp != MainLabel && comp != PerformanceLabel && comp != ActivitiesLabel) {
                MainPanel.remove(comp);
            }
        }
        MainPanel.add(newPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints
        (0, 0, MainPanel.getWidth(), MainPanel.getHeight()));
        
        MainPanel.revalidate();
        MainPanel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActivitiesLabel;
    private javax.swing.JButton GradeCalcButton;
    private javax.swing.JButton JavaParsingButton;
    private javax.swing.JLabel MainLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton NextPageButton;
    private javax.swing.JButton NumberFormattingButton;
    private javax.swing.JButton OpeningClosingWindowButton;
    private javax.swing.JLabel PerformanceLabel;
    private javax.swing.JButton SimpPayrollSystemButton;
    private javax.swing.JButton StudentFormButton;
    private javax.swing.JButton StudentRegFormButton;
    private javax.swing.JButton TempConverterButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
