/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package performancetasks;

import java.math.BigDecimal;
import java.math.MathContext;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.NumberFormat;

/**
 *
 * @author ihub27
 */

public class OldSimpleCalculator extends javax.swing.JFrame {
    private BigDecimal num1 = BigDecimal.ZERO;
    private char operator = 0;
    private BigDecimal lastNum2 = BigDecimal.ZERO;
    private boolean newInput = true;
    /**
     * Creates new form pt_calculator
     */
    public OldSimpleCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAC = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnPercent = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnDecimal = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        BtnRemoveOneChar = new javax.swing.JButton();
        btnOne = new javax.swing.JButton();
        txtDisplay = new javax.swing.JTextField();
        btnThree = new javax.swing.JButton();
        btnPlusMinus = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        txtDisplayHistory = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Calculator");
        setBackground(new java.awt.Color(102, 102, 102));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(35, 40, 43));

        btnAC.setBackground(new java.awt.Color(113, 117, 119));
        btnAC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAC.setForeground(new java.awt.Color(255, 255, 255));
        btnAC.setText("AC");
        btnAC.setMargin(new java.awt.Insets(2, 0, 3, 0));
        btnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACActionPerformed(evt);
            }
        });

        btnDivide.setBackground(new java.awt.Color(255, 139, 0));
        btnDivide.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDivide.setForeground(new java.awt.Color(255, 255, 255));
        btnDivide.setText("÷");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btnPercent.setBackground(new java.awt.Color(113, 117, 119));
        btnPercent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPercent.setForeground(new java.awt.Color(255, 255, 255));
        btnPercent.setText("%");
        btnPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercentActionPerformed(evt);
            }
        });

        btnMultiply.setBackground(new java.awt.Color(255, 139, 0));
        btnMultiply.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMultiply.setForeground(new java.awt.Color(255, 255, 255));
        btnMultiply.setText("×");
        btnMultiply.setMargin(new java.awt.Insets(2, 0, 3, 0));
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        btnSeven.setBackground(new java.awt.Color(69, 74, 79));
        btnSeven.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeven.setForeground(new java.awt.Color(255, 255, 255));
        btnSeven.setText("7");
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(255, 139, 0));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnNine.setBackground(new java.awt.Color(69, 74, 79));
        btnNine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNine.setForeground(new java.awt.Color(255, 255, 255));
        btnNine.setText("9");
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });

        btnSubtract.setBackground(new java.awt.Color(255, 139, 0));
        btnSubtract.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSubtract.setForeground(new java.awt.Color(255, 255, 255));
        btnSubtract.setText("-");
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });

        btnEight.setBackground(new java.awt.Color(69, 74, 79));
        btnEight.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEight.setForeground(new java.awt.Color(255, 255, 255));
        btnEight.setText("8");
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        btnDecimal.setBackground(new java.awt.Color(69, 74, 79));
        btnDecimal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDecimal.setForeground(new java.awt.Color(255, 255, 255));
        btnDecimal.setText(".");
        btnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecimalActionPerformed(evt);
            }
        });

        btnFour.setBackground(new java.awt.Color(69, 74, 79));
        btnFour.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFour.setForeground(new java.awt.Color(255, 255, 255));
        btnFour.setText("4");
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnZero.setBackground(new java.awt.Color(69, 74, 79));
        btnZero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnZero.setForeground(new java.awt.Color(255, 255, 255));
        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnSix.setBackground(new java.awt.Color(69, 74, 79));
        btnSix.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSix.setForeground(new java.awt.Color(255, 255, 255));
        btnSix.setText("6");
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnEqual.setBackground(new java.awt.Color(51, 51, 255));
        btnEqual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEqual.setForeground(new java.awt.Color(255, 255, 255));
        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        btnFive.setBackground(new java.awt.Color(69, 74, 79));
        btnFive.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFive.setForeground(new java.awt.Color(255, 255, 255));
        btnFive.setText("5");
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        BtnRemoveOneChar.setBackground(new java.awt.Color(113, 117, 119));
        BtnRemoveOneChar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnRemoveOneChar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRemoveOneChar.setText("←");
        BtnRemoveOneChar.setMargin(new java.awt.Insets(2, 0, 5, 0));
        BtnRemoveOneChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoveOneCharActionPerformed(evt);
            }
        });

        btnOne.setBackground(new java.awt.Color(69, 74, 79));
        btnOne.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnOne.setForeground(new java.awt.Color(255, 255, 255));
        btnOne.setText("1");
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        txtDisplay.setBackground(new java.awt.Color(35, 40, 43));
        txtDisplay.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtDisplay.setForeground(new java.awt.Color(255, 255, 255));
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDisplay.setText("0");
        txtDisplay.setBorder(null);
        txtDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDisplayKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDisplayKeyTyped(evt);
            }
        });

        btnThree.setBackground(new java.awt.Color(69, 74, 79));
        btnThree.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThree.setForeground(new java.awt.Color(255, 255, 255));
        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnPlusMinus.setBackground(new java.awt.Color(69, 74, 79));
        btnPlusMinus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPlusMinus.setForeground(new java.awt.Color(255, 255, 255));
        btnPlusMinus.setText("±");
        btnPlusMinus.setMargin(new java.awt.Insets(2, 0, 3, 0));
        btnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusMinusActionPerformed(evt);
            }
        });

        btnTwo.setBackground(new java.awt.Color(69, 74, 79));
        btnTwo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTwo.setForeground(new java.awt.Color(255, 255, 255));
        btnTwo.setText("2");
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        txtDisplayHistory.setBackground(new java.awt.Color(255, 255, 255));
        txtDisplayHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDisplayHistory.setForeground(new java.awt.Color(153, 153, 153));
        txtDisplayHistory.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDisplay)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(BtnRemoveOneChar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDisplayHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtDisplayHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRemoveOneChar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private String formatNumber(BigDecimal num){
        NumberFormat formatter = new DecimalFormat("0.0000000000000000E0");
        formatter.setRoundingMode(RoundingMode.HALF_UP);
        formatter.setMinimumFractionDigits((num.scale() > 0) ? num.precision() : num.scale());
        return formatter.format(num);
    }
    
    
    private String numCheck(BigDecimal result) {
//        if (result.abs().compareTo(new BigDecimal(Long.MAX_VALUE)) > 0) {
//            return overflow;
//        }
        if (result.stripTrailingZeros().toString().length() > 16) {
            System.out.println("foramatting");
            return formatNumber(result);
        }
        if (result.stripTrailingZeros().scale() <= 0) {
            System.out.println("hehehe");
           return result.toString();
        } else {
            System.out.println("sdadsadas");
           return result.toPlainString();
        }
    }
    
    private void updateDisplay(String text) {
        if (!newInput) {
                txtDisplay.setText("");
                newInput = true;
            }
        if (txtDisplay.getText().equals("0")) {
            txtDisplay.setText(text);
            return;
        }
            txtDisplay.setText(txtDisplay.getText() + text);
    }

    private void setOperator(String op) {
        if (!txtDisplay.getText().isEmpty()) {
                num1 = new BigDecimal(txtDisplay.getText());
            }
            operator = op.charAt(0);
            txtDisplayHistory.setText(numCheck(num1) + " " + operator);
            txtDisplay.setText("");
            newInput = true;
    }
    
    private void btnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACActionPerformed
        txtDisplay.setText("0");
        txtDisplayHistory.setText("");
        num1 = BigDecimal.ZERO;
        operator = 0;
        lastNum2 = BigDecimal.ZERO;
        newInput = true;
    }//GEN-LAST:event_btnACActionPerformed

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        updateDisplay("1");
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        updateDisplay("2");
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        updateDisplay("3");
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        updateDisplay("4");
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        updateDisplay("5");
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        updateDisplay("6");
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        updateDisplay("7");
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        updateDisplay("8");
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        updateDisplay("9");
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        updateDisplay("0"); 
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        setOperator("-");
    }//GEN-LAST:event_btnSubtractActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        setOperator("+");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        setOperator("×");
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        setOperator("÷");
    }//GEN-LAST:event_btnDivideActionPerformed

    private void calculate(){
        // If no operator selected, just display num1
        if (operator == 0) {
            if (!txtDisplay.getText().isEmpty()) {
                num1 = new BigDecimal(txtDisplay.getText());
            }
            // Display formatting
            txtDisplay.setText(numCheck(num1));
            txtDisplayHistory.setText(""); // clear history
            newInput = false;
            return;
        }

        BigDecimal num2;

        // If user typed new number, use it
        if (newInput && !txtDisplay.getText().isEmpty()) {
            num2 = new BigDecimal(txtDisplay.getText());
            lastNum2 = num2;
        } else {
            // Reuse lastNum2 for repeated '='
            num2 = lastNum2;
        }

        BigDecimal result = BigDecimal.ZERO;
        switch (operator) {
            case '+' -> result = num1.add(num2);
            case '-' -> result = num1.subtract(num2);
            case '×' -> result = num1.multiply(num2);
            case '÷' -> {
                            if (num2.compareTo(BigDecimal.ZERO) == 0) {
                                txtDisplay.setText("Cannot divide by zero");
                                return;
                            }
                            result = num1.divide(num2);
                        }   
        }

        if (result.toString().length() > 16) {
            txtDisplayHistory.setText(numCheck(num1) + " " + operator + " " + numCheck(num2) + " =");
            txtDisplay.setText(numCheck(result));
            System.out.println("ahahhaha");
        } else {
            txtDisplayHistory.setText(numCheck(num1) + " " + operator + " " + numCheck(num2) + " =");
            txtDisplay.setText(numCheck(result));
        }
        num1 = result;
        newInput = false;
    }
        
    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        calculate();
    }//GEN-LAST:event_btnEqualActionPerformed

    private void btnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusMinusActionPerformed
        try{
            num1 = new BigDecimal(txtDisplay.getText());
            num1 = num1.negate();
            txtDisplay.setText(num1.stripTrailingZeros().toPlainString());  
        }catch(NumberFormatException e){
            txtDisplay.setText("Error");
        }
    }//GEN-LAST:event_btnPlusMinusActionPerformed
    
    private boolean isOperator(char c){
        return c == '+' || c == '-' || c == '×' || c == '÷';
    }
    
    private boolean notAllowedCharacters(char c){
        String display = txtDisplay.getText();
        
        if (Character.isDigit(c)) return false;
        
        if (isOperator(c)) return false;
        
        if (c == '.'){
            int lastOperatorIndex = -1;
            for (int i = display.length() - 1; i >= 0; i--) {
                if (isOperator(display.charAt(i))) {
                    lastOperatorIndex = i;
                    break;
                }
            }
            String currentNumber = display.substring(lastOperatorIndex + 1);
            
            if (currentNumber.contains(".")) {
                return true;
            } else {
                return false;
            }
        }
        
        if (c == '\b') return false;
        
        return true;
    }
    
    private void txtDisplayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDisplayKeyTyped
//        char c = evt.getKeyChar();
//        String textFromDisplay = txtDisplay.getText();
//        if (notAllowedCharacters(c)){
//            evt.consume();
//        }
//        if (isOperator(c)) {
//            if (textFromDisplay.isEmpty() || isOperator(textFromDisplay.charAt(textFromDisplay.length() - 1))) {
//                evt.consume();
//            }
//        }
//        if (Character.isDigit(c)){
//            if (textFromDisplay.equals("0") || textFromDisplay.equals("0.0")){
//                txtDisplay.setText(String.valueOf(c));
//                evt.consume();
//                return;
//            }
//        }
//        try { 
//            firstNum = new BigDecimal(txtDisplay.getText());
//        }catch(NumberFormatException e){
//            txtDisplay.setText("Invalid Input");
//        }
//        
//        
//        if (textFromDisplay.equals("Invalid Input")){
//            if(Character.isDigit(c)){
//                txtDisplay.setText(String.valueOf(c));
//                evt.consume();
//            } else {
//                evt.consume();
//            }
//        }
    }//GEN-LAST:event_txtDisplayKeyTyped

    private void btnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecimalActionPerformed
        if (!txtDisplay.getText().contains(".")) {
            if (!newInput) {
                txtDisplay.setText("0");
                newInput = true;
            }
            txtDisplay.setText(txtDisplay.getText() + ".");
        }
    }//GEN-LAST:event_btnDecimalActionPerformed

    private void btnPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercentActionPerformed
        try {
            num1 = new BigDecimal(txtDisplay.getText());
            BigDecimal result = num1.divide(new BigDecimal("100"));
            txtDisplay.setText(result.stripTrailingZeros().toPlainString());
            txtDisplayHistory.setText(result.stripTrailingZeros().toPlainString() +" / 100");
        } catch (NumberFormatException e){
            txtDisplay.setText("Error");
        }
    }//GEN-LAST:event_btnPercentActionPerformed

    private void BtnRemoveOneCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoveOneCharActionPerformed
//        String text = txtDisplay.getText();
//
//        if(text.contains("Cannot divide by zero") || text.contains("Invalid Input")){
//                txtDisplay.setText("0");
//                errorState = false;
//                return;
//        }
//        if(text.length() > 0){
//            StringBuilder stB = new StringBuilder(text);
//            stB.deleteCharAt(text.length() - 1);
//            String updatedText = stB.toString();
//            if(updatedText.isEmpty() || updatedText.equals("-")) {
//                txtDisplay.setText("0");
//            } else {
//                txtDisplay.setText(updatedText);
//            }
//        } 
    }//GEN-LAST:event_BtnRemoveOneCharActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void txtDisplayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDisplayKeyReleased

    }//GEN-LAST:event_txtDisplayKeyReleased
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OldSimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OldSimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OldSimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OldSimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OldSimpleCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRemoveOneChar;
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDecimal;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPercent;
    private javax.swing.JButton btnPlusMinus;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDisplay;
    private javax.swing.JLabel txtDisplayHistory;
    // End of variables declaration//GEN-END:variables
}
