/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package performancetasks;

import javax.swing.JOptionPane;

/**
 *
 * @author seany
 */
public class pt_gradecalculator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(pt_gradecalculator.class.getName());

    /**
     * Creates new form pt_gradecalculator
     */
    public pt_gradecalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLiterature = new javax.swing.JTextField();
        txtProg = new javax.swing.JTextField();
        computeBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPE = new javax.swing.JTextField();
        txtScience = new javax.swing.JTextField();
        txtPR = new javax.swing.JTextField();
        txtSTATS = new javax.swing.JTextField();
        txtFilipino = new javax.swing.JTextField();
        txtRAWS = new javax.swing.JTextField();
        goBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Grade Calculator");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Grade Calculator");

        jLabel2.setText("Statistics and Probability Grade");

        jLabel3.setText("Physical Science Grade");

        txtLiterature.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLiteratureKeyTyped(evt);
            }
        });

        txtProg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProgKeyTyped(evt);
            }
        });

        computeBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        computeBtn.setText("Compute");
        computeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Pagbasa at Pagsusuri Grade");

        jLabel6.setText("Reading and Writing Skills Grade");

        jLabel7.setText("Computer Programming Grade");

        jLabel8.setText("Practical Research 1 Grade");

        jLabel9.setText("Physical Education Grade");

        jLabel10.setText("21st Century Literature Grade");

        txtPE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPEKeyTyped(evt);
            }
        });

        txtScience.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtScienceKeyTyped(evt);
            }
        });

        txtPR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPRKeyTyped(evt);
            }
        });

        txtSTATS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSTATSKeyTyped(evt);
            }
        });

        txtFilipino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFilipinoKeyTyped(evt);
            }
        });

        txtRAWS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRAWSKeyTyped(evt);
            }
        });

        goBackBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        goBackBtn.setText("Go Back");
        goBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRAWS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(69, 69, 69)
                                    .addComponent(txtScience, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(24, 24, 24)
                                        .addComponent(txtProg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(36, 36, 36)
                                        .addComponent(txtLiterature, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFilipino, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtSTATS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(70, 70, 70))))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(computeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(goBackBtn)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtLiterature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFilipino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtScience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSTATS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRAWS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(computeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean isGradeValid(double grade){
        return grade>=60 && grade<=100;
    }
    
    private boolean areGradesValid(double[] grades){
        for (double grade : grades){
            if (!isGradeValid(grade)){
                return false;
            }
        }
        return true;
    }
    
    private void errorMessages(String type){
        String message;
        switch(type.toLowerCase()){
            case "input range" -> message = "Please input grades in a range between 60-100!";
            case "invalid input" -> message = "Invalid Input. Please check your inputs.";
            default -> message = "An unexpected error occured.";
        }
        JOptionPane.showMessageDialog(
                pt_gradecalculator.this,
                message,
                "Invalid Input!",
        JOptionPane.ERROR_MESSAGE);
    }
    
    private void message(double average){
        String message;
            
            if (average >= 75 && average < 90 ) {
                message ="<html><b><font color='green'>You Passed!<br>Average: " +String.format("%.2f", average)+"</font></b></html>";
            }else if (average >= 90 && average < 95) {
                message ="<html><b><font color='green'>You Passed! With Honors!<br>Average: " +String.format("%.2f", average)+"</font></b></html>";
            } else if (average >= 95 && average < 98) {
                message="<html><b><font color='green'>You Passed! With High Honors!<br>Average: " +String.format("%.2f", average)+"</font></b></html>";
            } else if (average >= 98 ) {
                message="<html><b><font color='green'>You Passed! With Highest Honors!<br>Average: " +String.format("%.2f", average)+"</font></b></html>";                        
            } else {
                message="<html><b><font color='red'>You Failed!<br>Average: " +String.format("%.2f", average)+"</font></b></html>";
            }
            
            JOptionPane.showMessageDialog(
                pt_gradecalculator.this,
                message,
                "GRADE CALCULATOR",
            JOptionPane.INFORMATION_MESSAGE);
            
            
    }
    
    private void computeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeBtnActionPerformed
        try {
            double[] grades = {
                   Double.parseDouble(txtLiterature.getText()),
                   Double.parseDouble(txtProg.getText()),
                   Double.parseDouble(txtRAWS.getText()),
                   Double.parseDouble(txtPE.getText()),
                   Double.parseDouble(txtPR.getText()),
                   Double.parseDouble(txtSTATS.getText()),
                   Double.parseDouble(txtScience.getText()),
                   Double.parseDouble(txtFilipino.getText())
            };
            
            if(!areGradesValid(grades)){
                errorMessages("input range");
                return;
            }
            
            double sum = 0;
            for (double grade : grades) {
                sum += grade;
            }
            double average = sum/grades.length;
            
            message(average);
            
            
        } catch (NumberFormatException e) {
            errorMessages("invalid input");
        }
    }//GEN-LAST:event_computeBtnActionPerformed
    
    private void isValidInput(java.awt.event.KeyEvent evt, javax.swing.JTextField textField){
        char c = evt.getKeyChar();
        String text = textField.getText();
        if (Character.isDigit(c)) {
            if (text.length()>5) {
                evt.consume();
            }
            return;
        }
        if (c=='.') {
            if(text.contains(".")){
                evt.consume();
            }
            return;
        }
        evt.consume();
    }
    
    private void txtLiteratureKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLiteratureKeyTyped
        isValidInput(evt, txtLiterature);
    }//GEN-LAST:event_txtLiteratureKeyTyped

    private void txtProgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProgKeyTyped
        isValidInput(evt, txtProg);
    }//GEN-LAST:event_txtProgKeyTyped

    private void txtPEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPEKeyTyped
       isValidInput(evt, txtPE);
    }//GEN-LAST:event_txtPEKeyTyped

    private void txtScienceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtScienceKeyTyped
        isValidInput(evt, txtScience);
    }//GEN-LAST:event_txtScienceKeyTyped

    private void txtPRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPRKeyTyped
        isValidInput(evt, txtPR);
    }//GEN-LAST:event_txtPRKeyTyped

    private void txtSTATSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSTATSKeyTyped
        isValidInput(evt, txtSTATS);
    }//GEN-LAST:event_txtSTATSKeyTyped

    private void txtFilipinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilipinoKeyTyped
        isValidInput(evt, txtFilipino);
    }//GEN-LAST:event_txtFilipinoKeyTyped

    private void txtRAWSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRAWSKeyTyped
        isValidInput(evt, txtRAWS);
    }//GEN-LAST:event_txtRAWSKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to close the application?", "Message", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void goBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackBtnActionPerformed
        MainMenuOfApplications mainmenuApp = new MainMenuOfApplications();
        mainmenuApp.setLocationRelativeTo(this);
        mainmenuApp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goBackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new pt_gradecalculator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton computeBtn;
    private javax.swing.JButton goBackBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtFilipino;
    private javax.swing.JTextField txtLiterature;
    private javax.swing.JTextField txtPE;
    private javax.swing.JTextField txtPR;
    private javax.swing.JTextField txtProg;
    private javax.swing.JTextField txtRAWS;
    private javax.swing.JTextField txtSTATS;
    private javax.swing.JTextField txtScience;
    // End of variables declaration//GEN-END:variables
}
