/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package performancetasks;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author ihub27
 */
public class pt_simplepayrollsystem extends javax.swing.JFrame {

    /**
     * Creates new form pt_payroll
     */
    public pt_simplepayrollsystem() {
        initComponents();
        rateperhour();
    }
    
    private void rateperhour(){
        Locale localePH = Locale.forLanguageTag("en-PH");
        
        NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(localePH);
        currencyFormat.setGroupingUsed(false);
        
        NumberFormatter currencyFormatter = new NumberFormatter(currencyFormat);
        currencyFormatter.setAllowsInvalid(false);
        currencyFormatter.setOverwriteMode(false);
        
        rateperHourField.setFormatterFactory(new DefaultFormatterFactory(currencyFormatter));
        rateperHourField.addPropertyChangeListener("value", evt ->{
            if(rateperHourField.getValue() == null){
                rateperHourField.setValue(0.00);
            }
        });
        rateperHourField.setValue(0.00);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        computeBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        rateperHourField = new javax.swing.JFormattedTextField();
        employeeNameField = new javax.swing.JTextField();
        hoursWorkedField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Employee Name:");

        jLabel2.setText("Hours Worked:");

        jLabel3.setText("Rate per hour:");

        computeBtn.setText("Compute");
        computeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        rateperHourField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateperHourFieldActionPerformed(evt);
            }
        });

        employeeNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNameFieldActionPerformed(evt);
            }
        });
        employeeNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                employeeNameFieldKeyTyped(evt);
            }
        });

        hoursWorkedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursWorkedFieldActionPerformed(evt);
            }
        });
        hoursWorkedField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hoursWorkedFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(employeeNameField)
                            .addComponent(hoursWorkedField)
                            .addComponent(rateperHourField, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(computeBtn)
                        .addGap(18, 18, 18)
                        .addComponent(clearBtn)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(employeeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hoursWorkedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rateperHourField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(computeBtn)
                    .addComponent(clearBtn))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeNameFieldKeyTyped
        char c = evt.getKeyChar();
        if(Character.isAlphabetic(c)){
            return;
        }
        if(c == ' '){
            if(employeeNameField.getCaretPosition() == 0){
                evt.consume();
            }
            return;
        }
        evt.consume();
    }//GEN-LAST:event_employeeNameFieldKeyTyped

    private void hoursWorkedFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hoursWorkedFieldKeyTyped
        char c = evt.getKeyChar();
        String text = hoursWorkedField.getText();
        if(Character.isDigit(c)){
            if(text.length()>=3){
                evt.consume();
            }
            return;
        }
        evt.consume();
    }//GEN-LAST:event_hoursWorkedFieldKeyTyped

    private void employeeNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNameFieldActionPerformed

    private void hoursWorkedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursWorkedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursWorkedFieldActionPerformed

    private void rateperHourFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateperHourFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateperHourFieldActionPerformed
    
    private void deductions(double grossPay){
        double SSSDeduction = grossPay * 0.05;
        double PhilHealthDeduction = grossPay * 0.025;
        double PagIbigDeduction = grossPay * 0.02;
        double TaxDeduction = grossPay * 0.2;
        double[] totalDeductions = { SSSDeduction, PhilHealthDeduction, PagIbigDeduction, TaxDeduction};
        for (double deductions : totalDeductions) {
            double netPay = grossPay - deductions;
        }
        
    }
    
    private double grossPay(){
        try {
            double hrsWorked = Double.valueOf(hoursWorkedField.getText());
            double rateperHr = ((Number) 
                    rateperHourField.getValue()).doubleValue();
            double grossPay = hrsWorked * rateperHr;
            return grossPay;
        } catch(NumberFormatException e){
            System.out.println("Error Parsing");
            return 0;
        }
    }
    
    private void computeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeBtnActionPerformed
        deductions(grossPay());
    }//GEN-LAST:event_computeBtnActionPerformed
    
    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        employeeNameField.setText("");
        hoursWorkedField.setText("");
        rateperHourField.setValue(0.00);
    }//GEN-LAST:event_clearBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pt_simplepayrollsystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton computeBtn;
    private javax.swing.JTextField employeeNameField;
    private javax.swing.JTextField hoursWorkedField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField rateperHourField;
    // End of variables declaration//GEN-END:variables
}
