/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package performancetasks;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author ihub27
 */
public class pt_studentregform extends javax.swing.JFrame {
private static final String EMAIL_PATTERN = 
        "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    /**
     * Creates new form pt_studentregform
     */
    public pt_studentregform() {
        initComponents();
        DocumentListener passwordListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                checkPasswords();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkPasswords();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                checkPasswords();
            }
        };
        txtPassword.getDocument().addDocumentListener(passwordListener);
        txtconfPassword.getDocument().addDocumentListener(passwordListener);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        studentFirstName = new javax.swing.JLabel();
        studentLastName = new javax.swing.JLabel();
        EmailAddress = new javax.swing.JLabel();
        confEmailAddress = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        confPassword = new javax.swing.JLabel();
        txtstudentFN = new javax.swing.JTextField();
        txtstudentLN = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtconfEmailAddress = new javax.swing.JTextField();
        DateofBirth = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        ifMale = new javax.swing.JRadioButton();
        ifFemale = new javax.swing.JRadioButton();
        txtPassword = new javax.swing.JPasswordField();
        txtconfPassword = new javax.swing.JPasswordField();
        Year = new javax.swing.JComboBox<>();
        Month = new javax.swing.JComboBox<>();
        Day = new javax.swing.JComboBox<>();
        submitBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        Department = new javax.swing.JLabel();
        Civil = new javax.swing.JRadioButton();
        compSciandEngr = new javax.swing.JRadioButton();
        Electrics = new javax.swing.JRadioButton();
        ElectronicsandCommunication = new javax.swing.JRadioButton();
        Mechanical = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentData = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Registration Form");
        setResizable(false);

        studentFirstName.setText("Student First Name");
        studentFirstName.setToolTipText("");
        studentFirstName.setName(""); // NOI18N

        studentLastName.setText("Student Last Name");

        EmailAddress.setText("Email Address");

        confEmailAddress.setText("Confirm Email Address");

        Password.setDisplayedMnemonic('p');
        Password.setText("Password");

        confPassword.setText("Confirm Password");

        txtstudentFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudentFNActionPerformed(evt);
            }
        });

        txtstudentLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudentLNActionPerformed(evt);
            }
        });

        txtEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddressActionPerformed(evt);
            }
        });

        txtconfEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfEmailAddressActionPerformed(evt);
            }
        });

        DateofBirth.setText("Date of Birth");

        sex.setText("Sex");

        buttonGroup1.add(ifMale);
        ifMale.setText("Male");

        buttonGroup1.add(ifFemale);
        ifFemale.setText("Female");

        Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", " " }));

        Month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        Day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        Department.setText("Department");

        buttonGroup2.add(Civil);
        Civil.setText("Civil");

        buttonGroup2.add(compSciandEngr);
        compSciandEngr.setText("Computer Science and Engineer");

        buttonGroup2.add(Electrics);
        Electrics.setText("Electrics");

        buttonGroup2.add(ElectronicsandCommunication);
        ElectronicsandCommunication.setText("Electronics and Communication");

        buttonGroup2.add(Mechanical);
        Mechanical.setText("Mechanical");

        studentData.setEditable(false);
        studentData.setColumns(20);
        studentData.setRows(5);
        jScrollPane1.setViewportView(studentData);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Your Data is Below");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("New Student Registration Form");

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setName(""); // NOI18N
        errorLabel.setPreferredSize(new java.awt.Dimension(200, 12));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentFirstName)
                            .addComponent(studentLastName)
                            .addComponent(EmailAddress)
                            .addComponent(confEmailAddress)
                            .addComponent(Password)
                            .addComponent(confPassword))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtconfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtconfEmailAddress)
                                .addComponent(txtEmailAddress)
                                .addComponent(txtstudentLN)
                                .addComponent(txtstudentFN)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateofBirth)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Department)
                                    .addComponent(sex))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Civil)
                                        .addGap(12, 12, 12)
                                        .addComponent(Electrics)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Mechanical))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ifMale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ifFemale))
                                    .addComponent(ElectronicsandCommunication)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(compSciandEngr)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(submitBtn)
                                .addGap(18, 18, 18)
                                .addComponent(clearBtn)
                                .addGap(18, 18, 18)
                                .addComponent(cancelBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentFirstName)
                    .addComponent(txtstudentFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentLastName)
                    .addComponent(txtstudentLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailAddress)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confEmailAddress)
                    .addComponent(txtconfEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password))
                .addGap(2, 2, 2)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confPassword)
                    .addComponent(txtconfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DateofBirth)
                            .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ifMale)
                                    .addComponent(ifFemale)
                                    .addComponent(sex))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Civil)
                                    .addComponent(Electrics)
                                    .addComponent(Mechanical)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(Department)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compSciandEngr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ElectronicsandCommunication)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitBtn)
                            .addComponent(clearBtn)
                            .addComponent(cancelBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtstudentFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentFNActionPerformed

    private void checkPasswords() {
        String password = new String(txtPassword.getPassword());
        String confirmPassword = new String(txtconfPassword.getPassword());

        if (password.isEmpty() && confirmPassword.isEmpty()) {
            errorLabel.setText("");
        } else if (!password.equals(confirmPassword)) {
            errorLabel.setText("Passwords do not match!");
        } else {
            errorLabel.setText("");
        }
    }
    private void txtstudentLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentLNActionPerformed

    private void txtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddressActionPerformed

    private void txtconfEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfEmailAddressActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        txtstudentFN.setText("");
        txtstudentLN.setText("");
        txtEmailAddress.setText("");
        txtconfEmailAddress.setText("");
        txtPassword.setText("");
        txtconfPassword.setText("");
        studentData.setText("");
        //emailnotmatch.setVisible(false);
        //passnotmatch.setVisible(false);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        studentData.setText("");
        String FN = txtstudentFN.getText();
        String LN = txtstudentLN.getText();
        if (FN.isBlank()||LN.isBlank()){
            JOptionPane.showMessageDialog(
                        pt_studentregform.this,
                        "Name field cannot be empty!",
                        "Input Error",
                        JOptionPane.ERROR_MESSAGE
                    );
        } else {
            studentData.append("Name: "+FN+" "+LN);
        }
        
        String emailAddress = txtEmailAddress.getText(), confEmailAddress = txtconfEmailAddress.getText();
        if (emailAddress.isBlank()||confEmailAddress.isBlank()){
            
        } else {
            if (emailAddress.equalsIgnoreCase(confEmailAddress)){
                studentData.append("\nEmail: "+ confEmailAddress);
            } else {
                //emailnotmatch.setVisible(true);
                studentData.setText("");
                JOptionPane.showMessageDialog(pt_studentregform.this,
                "Email or Password does not match!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            }
        }
        String password = String.valueOf(txtPassword.getPassword()), confPassword = String.valueOf(txtconfPassword.getPassword());
        if (password.isBlank() || confPassword.isBlank()){
            
        } else {
            if (password.equals(confPassword)) {
                studentData.append("\nPassword: "+confPassword);
            } else {
                //passnotmatch.setVisible(true);
                txtPassword.setText("");
                txtconfPassword.setText("");
                studentData.setText("");
                JOptionPane.showMessageDialog(pt_studentregform.this,
                "Email or Password does not match!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            }    
        }
        int year = Year.getSelectedIndex(), month = Month.getSelectedIndex(), day = Day.getSelectedIndex();
        if (year == 0 || month == 0 || day == 0) {
            JOptionPane.showMessageDialog(pt_studentregform.this,
            "Must Enter a Birth Date!",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        } else {
            studentData.append("\nBirthday: "+ Month.getSelectedItem().toString() + " " + Day.getSelectedItem().toString() +" " +  Year.getSelectedItem().toString());
        }
        

    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     *
     * @param args
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pt_studentregform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pt_studentregform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pt_studentregform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pt_studentregform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pt_studentregform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Civil;
    private javax.swing.JLabel DateofBirth;
    private javax.swing.JComboBox<String> Day;
    private javax.swing.JLabel Department;
    private javax.swing.JRadioButton Electrics;
    private javax.swing.JRadioButton ElectronicsandCommunication;
    private javax.swing.JLabel EmailAddress;
    private javax.swing.JRadioButton Mechanical;
    private javax.swing.JComboBox<String> Month;
    private javax.swing.JLabel Password;
    private javax.swing.JComboBox<String> Year;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JRadioButton compSciandEngr;
    private javax.swing.JLabel confEmailAddress;
    private javax.swing.JLabel confPassword;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JRadioButton ifFemale;
    private javax.swing.JRadioButton ifMale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sex;
    private javax.swing.JTextArea studentData;
    private javax.swing.JLabel studentFirstName;
    private javax.swing.JLabel studentLastName;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtconfEmailAddress;
    private javax.swing.JPasswordField txtconfPassword;
    private javax.swing.JTextField txtstudentFN;
    private javax.swing.JTextField txtstudentLN;
    // End of variables declaration//GEN-END:variables
}
