/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package performancetasks;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author ihub27
 */
public class pt_simplepayrollsystem extends javax.swing.JFrame {
    
    private NumberFormat currencyFormat;
    /**
     * Creates new form pt_payroll
     */
    public pt_simplepayrollsystem() {
        initComponents();
        setupCurrencyField();
    }
    
    private void setupCurrencyField(){
        Locale localePH = Locale.forLanguageTag("en-PH");
        
        NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(localePH);
        // need to fix
        NumberFormatter currencyFormatter = new NumberFormatter(currencyFormat);
        currencyFormatter.setAllowsInvalid(false);
        currencyFormatter.setOverwriteMode(false);
        
        hourlyRateField.setFormatterFactory(new DefaultFormatterFactory(currencyFormatter));
        hourlyRateField.addPropertyChangeListener("value", evt ->{
            if(hourlyRateField.getValue() == null){
                hourlyRateField.setValue(0.00);
            }
        });
        hourlyRateField.setValue(0.00);
    }
    
    public class payrollResult{
        private double totalDeductions;
        private double netPay;
        
        public payrollResult(double totalDeductions, double netPay){
            this.totalDeductions = totalDeductions;
            this.netPay = netPay;
        }
        
        
        public double getTotalDeductions(){
            return totalDeductions;
        }
        
        public double getNetPay(){
            return netPay;
        }
    }
    
    private payrollResult computeDeductions(double grossPay){
        double SSSDeduction = grossPay * 0.05;
        double PhilHealthDeduction = grossPay * 0.025;
        double PagIbigDeduction = grossPay * 0.02;
        double TaxDeduction = grossPay * 0.2;
        double[] deductions = { 
            SSSDeduction, 
            PhilHealthDeduction, 
            PagIbigDeduction, 
            TaxDeduction
        };
        double totalDeductions = 0;
        for (double deduction : deductions) {
            totalDeductions += deduction;
        }
        double netPay = grossPay - totalDeductions;
        return new payrollResult(totalDeductions, netPay);
    }
    
    private double grossPay(){
        try {
            int hrsWorked = Integer.parseInt(hoursWorkedField.getText());
            double rateperHr = ((Number) 
                    hourlyRateField.getValue()).doubleValue();
            double grossPay = hrsWorked * rateperHr;
            return grossPay;
        } catch(NumberFormatException e){
            System.out.println("Error Parsing");
            return 0;
        }
    }
    
    private String displayPayrollSummary() {
        String employeeName = employeeNameField.getText();
        double grossPay = grossPay();
        payrollResult result = computeDeductions(grossPay);
        double totalDeductions = result.totalDeductions;
        double netPay = result.netPay;
        double SSSDeduction = grossPay * 0.05;
        double PhilHealthDeduction = grossPay * 0.025;
        double PagIbigDeduction = grossPay * 0.02;
        double TaxDeduction = grossPay * 0.2;
        
        String formattedNetPay = currencyFormat.format(netPay);
        String payrollSummary ="<html>Employee name: " + employeeName +"<br>"
                                +"Gross Pay: " + grossPay + "<br>" +
                                "Summary of Deductions:<br>"+
                                "SSS: " + SSSDeduction + "<br>" +
                                "Pag-ibig: " + PagIbigDeduction + "<br>" +
                                "PhilHealth: " + PhilHealthDeduction + "<br>" +
                                "Tax: " + TaxDeduction + "<br>" +
                                "Total Deductions: " + totalDeductions + "<br>" +
                                "Net Pay: " + formattedNetPay + "<html>";
        return payrollSummary;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        computeBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        hourlyRateField = new javax.swing.JFormattedTextField();
        employeeNameField = new javax.swing.JTextField();
        hoursWorkedField = new javax.swing.JTextField();
        dataLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Payroll System");
        setResizable(false);

        jLabel1.setText("Employee Name:");

        jLabel2.setText("Hours Worked:");

        jLabel3.setText("Hourly Rate:");

        computeBtn.setText("Compute");
        computeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        hourlyRateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyRateFieldActionPerformed(evt);
            }
        });

        employeeNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNameFieldActionPerformed(evt);
            }
        });
        employeeNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                employeeNameFieldKeyTyped(evt);
            }
        });

        hoursWorkedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursWorkedFieldActionPerformed(evt);
            }
        });
        hoursWorkedField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hoursWorkedFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(employeeNameField)
                            .addComponent(hoursWorkedField)
                            .addComponent(hourlyRateField, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addGap(117, 117, 117)
                        .addComponent(dataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(computeBtn)
                        .addGap(18, 18, 18)
                        .addComponent(clearBtn)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(employeeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hoursWorkedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hourlyRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(computeBtn)
                    .addComponent(clearBtn))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeNameFieldKeyTyped
        char c = evt.getKeyChar();
        if(Character.isAlphabetic(c)){
            return;
        }
        if(c == ' '){
            if(employeeNameField.getCaretPosition() == 0){
                evt.consume();
            }
            return;
        }
        evt.consume();
    }//GEN-LAST:event_employeeNameFieldKeyTyped

    private void hoursWorkedFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hoursWorkedFieldKeyTyped
        char c = evt.getKeyChar();
        String text = hoursWorkedField.getText();
        if(Character.isDigit(c)){
            if(text.length()>=3){
                evt.consume();
            }
            return;
        }
        evt.consume();
    }//GEN-LAST:event_hoursWorkedFieldKeyTyped

    private void employeeNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNameFieldActionPerformed

    private void hoursWorkedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursWorkedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursWorkedFieldActionPerformed

    private void hourlyRateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyRateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourlyRateFieldActionPerformed
    
    private void computeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeBtnActionPerformed
        dataLabel.setText(displayPayrollSummary());
    }//GEN-LAST:event_computeBtnActionPerformed
    
    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        employeeNameField.setText("");
        hoursWorkedField.setText("");
        hourlyRateField.setValue(0.00);
        dataLabel.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pt_simplepayrollsystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton computeBtn;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JTextField employeeNameField;
    private javax.swing.JFormattedTextField hourlyRateField;
    private javax.swing.JTextField hoursWorkedField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
