/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package performancetasks;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author seanyauder
 */
enum UnitOfTemperatures {
    CELSIUS("Celsius", "°C") {
        @Override
        public double toCelsius(double temp) {
            return temp;
        }
        @Override
        public double fromCelsius(double celsiusValue) {
            return celsiusValue;
        }

    },
    FAHRENHEIT("Fahrenheit", "°F") {
        @Override
        public double toCelsius(double value) {
            return (value - 32) * 5.0/9.0;
        }
        @Override
        public double fromCelsius(double celsiusValue) {
            return celsiusValue * 9.0/5.0 + 32;
        }

    },
    KELVIN("Kelvin", "K") {
        @Override
        public double toCelsius(double value) {
            return value - 273.15;
        }
        @Override
        public double fromCelsius(double celsiusValue){
            return celsiusValue + 273.15;
        }
    };

    private final String name;
    private final String symbol;
    
    UnitOfTemperatures(String name, String symbol){
        this.name = name;
        this.symbol = symbol;
    }

    public String getName(){
        return name;
    }
    public String getSymbol(){
        return symbol;
    }

    public abstract double toCelsius(double value);

    public abstract double fromCelsius(double celsiusValue);
}
public class pt_temperatureconverter extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(pt_temperatureconverter.class.getName());

    /**
     * Creates new form pt_temperatureconverter
     */
    public pt_temperatureconverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxconvertFrom = new javax.swing.JComboBox<>();
        cbxconvertTo = new javax.swing.JComboBox<>();
        userInput = new javax.swing.JTextField();
        computeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Converter");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Temperature Converter");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("To");

        cbxconvertFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Unit-", "Celsius", "Fahrenheit", "Kelvin" }));
        cbxconvertFrom.setToolTipText("");

        cbxconvertTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Unit-", "Celsius", "Fahrenheit", "Kelvin" }));

        userInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userInputKeyTyped(evt);
            }
        });

        computeBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        computeBtn.setText("Convert");
        computeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(computeBtn)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(cbxconvertFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cbxconvertTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxconvertFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxconvertTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(computeBtn)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void userInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userInputKeyTyped
        char c = evt.getKeyChar();
        String text = userInput.getText();
        if (Character.isDigit(c)) {
            if (text.length()>=10) {
                evt.consume();
            }
            return;
        }

        if (c=='.') {
            if(text.contains(".")){
                evt.consume();
            }
            return;
        }

        if (c == '-') {
            if(text.contains("-") || userInput.getCaretPosition() != 0){
                evt.consume();
            }
            return;
        }
        evt.consume();
    }//GEN-LAST:event_userInputKeyTyped

    private boolean isValidInput(){
        String input = userInput.getText().trim();
        if(input.isBlank()){
            errorMessage("Invalid Input");
            return false;
        }
        try {
            Double.valueOf(input);
            return true;
        } catch (NumberFormatException e) {
            errorMessage("Invalid Input");
            return false;
        }
    }
    private double convert(double value, UnitOfTemperatures unitFrom, UnitOfTemperatures unitTo) {
        double celsius = unitFrom.toCelsius(value);
        return unitTo.fromCelsius(celsius);
    }

    private void convertMessage(double value, UnitOfTemperatures unitFrom, UnitOfTemperatures unitTo){
        double result = convert(value, unitFrom, unitTo);
        String message = String.format("%.2f%s to %s is %.2f%s",
                                value, unitFrom.getSymbol(),
                                unitTo.getName(),
                                result, unitTo.getSymbol());
        JOptionPane.showMessageDialog(
            pt_temperatureconverter.this,
            message, 
            "Temperature Converter",
        JOptionPane.INFORMATION_MESSAGE);
    }
    private void errorMessage(String type){
        String message;
        switch(type.toLowerCase()){
            case "select conversion type" -> message = "Select conversion type!";
            case "no unit to convert to" -> message = "Select unit to convert to!";
            case "no unit to convert from" -> message = "Select unit to convert from!";
            case "temperature cannot be converted to itself" -> message = "Temperature cannot be converted to itself!";
            case "invalid input" -> message = "Invalid Input. Please enter a valid number.";
            default -> message = "An unexpected error occurred.";
        }
        JOptionPane.showMessageDialog(
            pt_temperatureconverter.this,
            message,
            "Error",
        JOptionPane.ERROR_MESSAGE);
    }

    private void computeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeBtnActionPerformed
        int from = cbxconvertFrom.getSelectedIndex(), to = cbxconvertTo.getSelectedIndex();
        if (!isValidInput()){
          return;
        }
        if (from == 0 && to == 0){
            errorMessage("select conversion type");
            return;
        }
        if (from == 0) {
            errorMessage("no unit to convert from");
            return;
        }
        if (to == 0) {
            errorMessage("no unit to convert to");
            return;
        }
        
        UnitOfTemperatures unitFrom = UnitOfTemperatures.values()[from - 1], unitTo = UnitOfTemperatures.values()[to - 1];
        
        if (unitFrom == unitTo) {
            errorMessage("temperature cannot be converted to itself");
            return;
        }
        
        {
             double input = Double.parseDouble(userInput.getText().trim());
             convertMessage(input, unitFrom, unitTo);
        }
        
    }//GEN-LAST:event_computeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new pt_temperatureconverter().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxconvertFrom;
    private javax.swing.JComboBox<String> cbxconvertTo;
    private javax.swing.JButton computeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField userInput;
    // End of variables declaration//GEN-END:variables
}
