/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javacomponents_part1_activities;

import javax.swing.JOptionPane;
import performancetasks.*;


/**
 *
 * @author ihub27
 */
public class JavaParsing extends javax.swing.JFrame {

    /**
     * Creates new form JavaParsing
     */
    public JavaParsing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userinput1 = new javax.swing.JTextField();
        userinput2 = new javax.swing.JTextField();
        computeBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        operations = new javax.swing.JComboBox<>();
        goBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Advanced Calculator");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        userinput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userinput1ActionPerformed(evt);
            }
        });
        userinput1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userinput1KeyTyped(evt);
            }
        });

        userinput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userinput2ActionPerformed(evt);
            }
        });
        userinput2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userinput2KeyTyped(evt);
            }
        });

        computeBtn.setText("Compute");
        computeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Advanced Calculator");

        operations.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Operation-", "Addition", "Subtraction", "Multiplication", "Division" }));

        goBackBtn.setText("Go Back");
        goBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(operations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(computeBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(goBackBtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userinput2)
                                .addComponent(userinput1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userinput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userinput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(computeBtn)
                    .addComponent(goBackBtn))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void computeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeBtnActionPerformed
        try{ 
            int value1 = Integer.parseInt(userinput1.getText());
            int value2 = Integer.parseInt(userinput2.getText());
            int solution;
            int operation = operations.getSelectedIndex();
            
            switch(operation) {
                
                case 0 -> {
                    JOptionPane.showMessageDialog(
                        JavaParsing.this,
                        "Please Input an Operation!",
                        "Error",
                    JOptionPane.ERROR_MESSAGE);
                }
                case 1 -> {
                    solution = value1 + value2;
                    
                    JOptionPane.showMessageDialog(
                        JavaParsing.this,
                        "The answer is: " + solution,
                        "Solution",
                    JOptionPane.INFORMATION_MESSAGE);
                }
                case 2 -> {
                    solution = value1 - value2;
                    
                    JOptionPane.showMessageDialog(
                        JavaParsing.this,
                        "The answer is: " + solution,
                        "Solution",
                    JOptionPane.INFORMATION_MESSAGE);
                }
                case 3 -> {
                    solution = value1 * value2;
                    
                    JOptionPane.showMessageDialog(
                        JavaParsing.this,
                        "The answer is: " + solution,
                        "Solution",
                    JOptionPane.INFORMATION_MESSAGE);
                }
                case 4 -> {
                    try {
                    solution = value1 / value2;
                    
                    JOptionPane.showMessageDialog(
                        JavaParsing.this,
                        "The answer is: " + solution,
                        "Solution",
                    JOptionPane.INFORMATION_MESSAGE);
                    } catch (ArithmeticException e) {
                        JOptionPane.showMessageDialog(
                        JavaParsing.this,
                        "Cannot be divisible by 0!",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (NumberFormatException E) {
            JOptionPane.showMessageDialog(
                    JavaParsing.this,
                    "Error! Must input a number",
                    "Invalid Input",
            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_computeBtnActionPerformed

    private void userinput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userinput1ActionPerformed
        
    }//GEN-LAST:event_userinput1ActionPerformed

    private void userinput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userinput2ActionPerformed
       
    }//GEN-LAST:event_userinput2ActionPerformed

    private void userinput1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userinput1KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_userinput1KeyTyped

    private void userinput2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userinput2KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_userinput2KeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to close the application?", "Message", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void goBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackBtnActionPerformed
        MainMenuOfApplications mainmenuApp = new MainMenuOfApplications();
        mainmenuApp.setLocationRelativeTo(this);
        mainmenuApp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goBackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaParsing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaParsing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaParsing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaParsing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaParsing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton computeBtn;
    private javax.swing.JButton goBackBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> operations;
    private javax.swing.JTextField userinput1;
    private javax.swing.JTextField userinput2;
    // End of variables declaration//GEN-END:variables
}
